### ISSUE TITLE
Can't subscribe addresses

### ISSUE THREAD

**Issue by rienkwarners** [drewm/mailchimp-api#100]
Hi all,

We came across a weird bug, we can use the get('lists'); function, this returns the complete array with lists. We can also delete subscribers with the delete(''); function. But the post and put functions for new subscribe isn't working. The page return nothing (sometimes a 500 header). 

Even when I put a echo at the top, bottom or middle of the page, the echo doesn't get displayed. 

Checked the PHP version of the server: 5.3.3-7+squeeze27

Can somebody help me out? 

Thanks!

**Comment by Yunyun548** [comment]
I have made the subscribing work on Symfony with the following code
`
$MailChimp = new MailChimp($this->container->getParameter('mailchimp_api_key'));
            $list_id = $this->container->getParameter('mailchimp_list_id');

            $result = $MailChimp->post("lists/$list_id/members", [
                    'email_address' => $email,
                    'status'        => 'subscribed',
                ]);

            if ($MailChimp->success()) {
                return new JsonResponse(json_encode(array('message' => 'Votre demande a bien été enregistrée')), '200');
            } else {
                return new JsonResponse(json_encode(array('message' => "Vous avez déjà souscrit à la newsletter")), '200');
            }
`

However, this works on localhost but doesn't works in production, I always get an error back, in production
