### ISSUE TITLE
Request_successful == false. Why?

### ISSUE THREAD

**Issue by mrtutis** [drewm/mailchimp-api#102]
Hello,

I was trying everything, API key is really good, but I can't make the API working. I do not even see in mailchimp.com that there was some calls to the api. 
What is the problem?

https://gyazo.com/20c8e3231f12e5f8140f4463a0d30aec

It does not work on localhost and even in hosted server... 

Thank you

**Comment by drewm** [comment]
This isn't something I can help you with.
