### ISSUE TITLE
 unexpected 'use' (T_USE)

### ISSUE THREAD

**Issue by v3nt** [drewm/mailchimp-api#103]
Can't get this working?

[25-May-2016 16:42:04 UTC] PHP Parse error:  syntax error, unexpected 'use' (T_USE) in /Users/jynk/Projects/630_Wonkhe/web/wonkheweb/wp-content/themes/wonkhe-roots-master/lib/extras.php on line 72

71   include('MailChimp.php');
72  use \DrewM\MailChimp\MailChimp;

**Comment by v3nt** [comment]
i've put the files into /wp-contetn/theme/mytheme/lib/ if that affects the namespacing?

**Comment by terrymun** [comment]
You'll have to move `use` to the top of the file. It cannot be scoped or wrapped inside a function.

**Comment by ginxy33** [comment]
can you let me know how to unsubscribe to these e-mails?

Thanks,
Karen

**Comment by fiveminuteargument** [comment]
@ginxy33 go to https://github.com/watching then either "unwatch" or "change notification settings" depending on exactly what you want to do
