### ISSUE TITLE
Return Interest Groups

### ISSUE THREAD

**Issue by bstookey** [drewm/mailchimp-api#105]
$result = $MailChimp->get('lists'); // Fantastic!

$result = $MailChimp->get('lists/interest-groupings/ad92e55e29'); // No Go!!!

$result = $MailChimp->get('lists/ad92e55e29/interest-groupings'); // No Go!!!

$result = $MailChimp->call("lists/interest-groupings", array(
  "id": "ad92e55e29",
  "counts": false
)); // No Go

How do I return the list from a group?

**Comment by terrymun** [comment]
Are you referring to [*interest categories*](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/interest-categories/#)?

**Comment by bstookey** [comment]
Yes sir, Thank you for your response.

**Comment by bstookey** [comment]
$result = $MailChimp->get('/lists/ad92e55e29/interest-categories/350677/interests'); // No go

**Comment by prsrichard** [comment]
looks like you jumped over the 'specific interest-category-id' in your GET url

url-syntax for this call should look something like this:
/lists/SPECIFIC_LIST_ID/interest-categories/SPECIFIC_INTEREST_CATEGORY_ID/interests/SPECIFIC_INTEREST_ID

try calling:
`/lists/ad92e55e29/interest-categories`
to get your specific 'group' / interest-category - id

if you got your interest-category-id, you can go one step further to get all interests of that interest-category (group)
`/lists/ad92e55e29/interest-categories/INSERT_YOUR_INTEREST_CATEGORY_ID_HERE/interests`
.. and so on

try using the 'mailchimp playground' for navigating through the api

**Comment by wcoppens** [comment]
@prsrichard 

I understand this wrapper is a 1:1 mapping with the Mailchimp V3 API. However i've been wondering use cases in which you for instance require to fetch all interests of each group (for example having 5 groups with each 3 interests), wouldn't that result in way to much round-trips between client and server? I've been reading the docs quite intensively now and haven't found a viable solution to this problem, have you?

Just wondering what your thoughts are about this.

**Comment by bstookey** [comment]
@prsrichard helped me by referring me to the 'Mailchimp Playground' where I could find the specific ids needed. I am pulling the interests from only one category and outputting them in a custom form to be sent via ajax to the API to add members to the requested group(s). 

Although I have the form processing successfully via the API it will only do so if I use the Interest Category Name and Group Names and it throws an error "ad3xxx7890 is not a valid Interest Grouping id for the list My List Name".

Below is my function:

require_once 'MCAPI.class.php';
    $api = new MCAPI( '2823998ec0b59ffdbc2ace3cb93dcd1e-us11' );

    $checkboxes = isset( $_GET['checkbox'] ) ? $_GET['checkbox'] : array();

    $list_id = $_GET['list_id']; // this will through an error
    $list_name = $_GET['list_name']; // this is successful

    $interests = array();
    foreach ( $checkboxes as $interest ) {
        $interests[] = str_replace( ',', '\,', $interest ); // escape commas in named groups
    }
    $groups = implode( ",", $interests );

    $merge_vars = array(
        'EMAIL' => $_GET['email'],
        'FNAME' => $_GET['fname'],
        'LNAME' => $_GET['lname'],
        'GROUPINGS'=> array(
            0 => array (
                'name' => $list_name, // list_id here will through an error
                'groups'=>  $groups // groups as id's here will through an error
            )
        ),
        'double_optin'      => false,
        'update_existing'   => true,
        'replace_interests' => true,
        'send_welcome'      => true
    );

    if ( $api->listSubscribe( $list_id, $email, $merge_vars ) === true ) {
        // Success Message
        return '<strong><h3>Success!</h3> Check your inbox or spam folder for a message containing a confirmation link.</strong>';
    } else {
        // Error Message
        return '<b>Error:</b>&nbsp; ' . $api->errorMessage;
    }

**Comment by wturrell** [comment]
Re: reducing round trips, I'd suggest (and what I did was) caching the interest-category ids – for most applications they rarely change. (If you're lucky, you're using a framework with caching built in.)

**Comment by drzraf** [comment]
@bstookey did you finally found a way (API or not) to map between hexadecimal, mailchimp-provided group/interest ID and their integer counterparts?
