### ISSUE TITLE
Delete request always fails

### ISSUE THREAD

**Issue by rvanbaalen** [drewm/mailchimp-api#109]
When executing a Delete request, `$mailchimp->success()` always returns false and the `->getLastError()` returns an empty string.

As stated in the MailChimp API, a delete request does not respond with a JSON body. It simply returns headers.

**Comment by paperscissors** [comment]
the API returns a 204, so maybe the wrapper isn't checking for this?

**Comment by rvanbaalen** [comment]
Exactly. The wrapper assumes that an error has occurred when the response body is empty. However, for DELETE responses, the body is always empty.

**Comment by paperscissors** [comment]
Probably should just return true if the response is in the 200 range at all, even, regardless of body.

**Comment by rvanbaalen** [comment]
That would be a good fix

----
*Cattlea - Web Technology & Mobile Apps*

T: (+5999) 5229996
E: hello@cattlea.com

**Comment by drewm** [comment]
We're now doing this. Thanks for the feedback!

**Comment by rvanbaalen** [comment]
Nice!

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by paperscissors** [comment]
Thanks much!
