### ISSUE TITLE
magento custom controller

### ISSUE THREAD

**Issue by giorg** [drewm/mailchimp-api#111]
Hi,
I wrote a custom controller, I need to use your wrapper in there. So outside the controller class I did put
`use \DrewM\MailChimp\MailChimp;`
then inside
`include('./MailChimp.php');

        $MailChimp = new MailChimp('09cca428bec495a34492881b850af34f-us13');
        $result = $MailChimp->get('lists');

        print_r($result);die;`

but in the error log I see:

> 2016/06/22 10:23:53 [error] 14474#0: *60266 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'DrewM\MailChimp\MailChimp' not found in /var/www/magento/app/code/local/Hoop/Contact/controllers/ContactController.php on line 12"

MailChimp.php is located in the same folder of my controller.
Any hint?
Thanks a lot

**Comment by drewm** [comment]
This sounds very much like a Magento question - I don't think your problem would be any different with any other code you try to include.

I don't know anything about Magento, so you'd be better off asking somewhere where there are Magento users.
