### ISSUE TITLE
setting status to subscribe doesn’t work

### ISSUE THREAD

**Issue by nathanaelphilip** [drewm/mailchimp-api#112]
Is anyone else having trouble setting `status => subscribed` and it not take?
Does a domain need to be verified for this option to work?

**Comment by nathanaelphilip** [comment]
seems like an issue with the account.

**Comment by leolanzinger** [comment]
I am having problems as well, even though my POST req sets `status => 'subscribed'` I always get back `'pending'` in the response.

**Comment by drewm** [comment]
Do you think something about how the library is handling the request is inaccurate?

**Comment by nathanaelphilip** [comment]
@drewm in my case it was because the client’s account was suspended}. they had to contact MailChimp to get them to undo it. http://kb.mailchimp.com/accounts/compliance-reviews/why-accounts-get-suspended
