### ISSUE TITLE
Status isn't success on delete request

### ISSUE THREAD

**Issue by groomain** [drewm/mailchimp-api#114]
Hi,

Mailchimp seems te respond a HTTP 204 code when you try to delete something. HTTP 204 means success but mailchimp-api does not interpreted it as a success. 

It has to be a 200 response. It may be too strict?

```PHP
if (isset($d['status']) && $d['status'] != '200' && isset($d['detail'])) {
    $this->last_error = sprintf('%d: %s', $d['status'], $d['detail']);
} else {
    $this->request_successful = true;
}
```

What do you think?

Regards,

**Comment by drewm** [comment]
Is this the same as #109 ?

**Comment by groomain** [comment]
Yes exactly :) Sorry for the duplicate
