### ISSUE TITLE
HTTP response code

### ISSUE THREAD

**Issue by wturrell** [drewm/mailchimp-api#116]
Firstly thanks for making this – it's saved a considerable amount upgrading various legacy code to the v3 API recently.

Do you think there's a case for adding an `$http_code` private property and a `getLastHttpCode()` method?

**Example use case:** deleting a list member

`DELETE /lists/{list_id}/members/{subscriber_hash}`

If successful, this returns [204 (No content)](https://httpstatuses.com/204), and no response body.

However that means `$formattedResponse` is blank (specifically `bool false`.)  

So currently I end with code like this to check if the delete actually worked:

        $result = $this->MailChimp->delete($this->lists_endpoint($email));
        $response = $this->MailChimp->getLastResponse();
      
        if ($response['headers']['http_code'] == 204) {
            ...
        }

(I can do a PR if you like.)

Thanks,
William

**Comment by drewm** [comment]
I think the `204` response should now count for the `success()` method, so:

```php
$result = $this->MailChimp->delete($this->lists_endpoint($email));
if (!$this->MailChimp->success()) {
   ...
}
```

**Comment by wturrell** [comment]
Ah yep, that works. Thank you!
