### ISSUE TITLE
General Comments

### ISSUE THREAD

**Issue by smartinsight** [drewm/mailchimp-api#119]
Hi.

Great facility. Thank you.

Just a couple of comments that I think might help other users who are no too techhy...

1. The Mailchimp.pho file needs the <DC> variable changing when you start using this.
2. If you are using it with a php include "Mailchimp" , then remove the "use namespace DrewM\MailChimp;" line.

Hope this saves someone sometime!

**Comment by arximughal** [comment]
Mailchimp.php*
