### ISSUE TITLE
Returns "is already a list member" when email address isn't on the list

### ISSUE THREAD

**Issue by rickibarnes** [drewm/mailchimp-api#120]
So this is working great, except when I try to sign up a new member using post(), if they have _ever_ been a member of the list, it returns the error "Member Exists [status] => 400 [detail] => is already a list member". This is the case if the email address has been deleted and the member can no longer be seen or found on the list anywhere.

It's a bit of a weird one, that might be the desired behaviour for all I know. But then I'm not sure how to proceed.

It said I should use PUT instead, which then returns "Method Not Allowed. The requested method and resource are not compatible."

I'm sure it's probably obvious but I have literally not even the slightest idea how to proceed from here. Can you give me an example of how the PUT syntax would look? I assume that is what is at the root of the Method Not Allowed error.

**Comment by drewm** [comment]
This isn't anything this library is doing - that response is direct from MailChimp.

**Comment by rickibarnes** [comment]
Surely if I'm going to use PUT that relates to the library still, though?

**Comment by drzraf** [comment]
it's one of the numerous MailChimp API bugs
Tell their support.

**Comment by rickibarnes** [comment]
Ah OK thanks. I thought if I contacted them they'd be like "You're using a third party wrapper, don't tell us about it." :P

**Comment by rickibarnes** [comment]
Turns out the issue was actually that I was trying to use PUT without hashing the email address. You must hash to use PUT. I don't know if you therefore want to delete this thread or leave in case of future reference for others.

**Comment by cameronlockey** [comment]
I am having this same issue, though I am not using this lib. I have an email address that used to be a member of my contacts, and that I have deleted. I am trying to do a POST to the API, and am having the same scenario as the OP. So is that specific issue still a problem with the API itself?

Is the solution to just always MD5 the email address I want to add as a contact and PUT every time I want to add a new Member? Will that even work?

**Comment by siimtalts** [comment]
In case anyone has still this issue, I was able to solve mine by coverting th emails to lower case before hashing them. https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-put_lists_list_id_members_subscriber_hash
