### ISSUE TITLE
Create a campaign

### ISSUE THREAD

**Issue by webface** [drewm/mailchimp-api#122]
How do I create a campaign using this wrapper and pass parameters? Ive searched the internet and the documentation but their isn't enough information

$mc->post('campaigns');

just returns an error. Thanks in advance.

**Comment by drewm** [comment]
Please refer to the MailChimp API docs for the request body parameters you need to pass to create a campaign.

http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/

**Comment by webface** [comment]
A response like this would have been more helpful. But I'm leaving it in case anyone else needs it. Thanks anyway..

`$result = $MailChimp->post("campaigns", [
          'type' => 'regular',
          'recipients' => ['list_id' => 'xxx'],
          'settings' => ['subject_line' => 'Your Purchase Receipt',
                         'reply_to' => 'orders@example.com',
                         'from_name' => 'Customer Service']
            ]);`

**Comment by drewm** [comment]
Hey, it's not my job to help you figure out the MailChimp API. I don't have time to work up an example for every internet stranger who cruises by and asks a lazy, incomplete question.

There's a solid `post` example in the docs showing how to pass parameters, and everything else is in the MailChimp docs.

**Comment by webface** [comment]
My guess is you simply didn't understand the question. No need to be offensive

**Comment by drewm** [comment]
You're welcome. Enjoy the free software.
