### ISSUE TITLE
Unknown Error on subscribe, getMember

### ISSUE THREAD

**Issue by fabriciovieira** [drewm/mailchimp-api#123]
Hi!

I'm getting the _"Unknown error, call getLastResponse"_ in every call I try to to.  I'm running the 2.2.4 version.

**getLastRequest:**
`Array
(
    [method] => post
    [path] => lists/XXX/members
    [url] => https://usXX.api.mailchimp.com/3.0/lists/XXX/members
    [body] => {"email_address":"fvieira+laravel5@trendi.com.br","status":"subscribed","email_type":"html","merge_fields":{"firstName":"Fabricio","lastName":"Vines"}}
    [timeout] => 10
)
`

**getLastResponse**
```
Array
(
    [headers] => Array
        (
            [url] => https://usXX.api.mailchimp.com/3.0/lists/XXX/members
            [content_type] => 
            [http_code] => 0
            [header_size] => 0
            [request_size] => 0
            [filetime] => -1
            [ssl_verify_result] => 1
            [redirect_count] => 0
            [total_time] => 0.967
            [namelookup_time] => 0.015
            [connect_time] => 0.015
            [pretransfer_time] => 0
            [size_upload] => 0
            [size_download] => 0
            [speed_download] => 0
            [speed_upload] => 0
            [download_content_length] => -1
            [upload_content_length] => -1
            [starttransfer_time] => 0
            [redirect_time] => 0
            [redirect_url] => 
            [primary_ip] => 
            [certinfo] => Array
                (
                )

            [primary_port] => 443
            [local_ip] => 
            [local_port] => 60464
        )

    [body] => 
)
```

**Comment by drewm** [comment]
You're getting no response back at all. Check that your server has a clear path out to the web - you might need to talk to your server admin.

**Comment by apolyntsev** [comment]
Just try to increase request timeout. It helped me with the same problem.
