### ISSUE TITLE
Make a 'little' bit more advanced

### ISSUE THREAD

**Issue by holtkamp** [drewm/mailchimp-api#124]
> I hate complex wrappers. This lets you get from the MailChimp API docs to the code as directly as possible.

Ok, true, a brave stance 👍 , but have a look at this wrapper: https://github.com/jamesryanbell/cloudflare, it is 'simple' as well, but elegantly guides the user in using the proper methods, parameters and this way actual objects can be used instead of arrays etc. 

What do you think?

**Comment by drewm** [comment]
Something like that could be built, but it's not what I'm trying to do here.

**Comment by holtkamp** [comment]
Ok, understood 😄 , maybe I will try to come up with something that depends in your wrapper. Closing issue!
