### ISSUE TITLE
Check if user is subscribed

### ISSUE THREAD

**Issue by Messa1** [drewm/mailchimp-api#128]
Is there any way to only check if user is in a list?
Or get back in which lists user is subscribed?
I want to check before i update, create or delete a user.

Thanks, Matthias

**Comment by JohnGrefaldo** [comment]
Hi @Messa1 ,

I am assuming that:
User = lists member { /lists/{list_id}/members}
If not please disregard my comment.

You need to use the {subscriber_hash} .I think you have to view all users with their id's and check for their status if{subscribed, unsubscribed, cleaned, pending}. (**1**) then use the hash id to update or delete members.
http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#

In creating lists member you don't have to worry if it already exist mailchimp check if the member lists  arleady exist by email address. but if emails are diff but same name go back to (**1**).

e.g. snapshot
![image](https://cloud.githubusercontent.com/assets/21042198/18345830/ba3366cc-75ef-11e6-980e-b98231c23bc2.png)

Kind Regards,
John

**Comment by jzuleger3deluxe** [comment]
Hey everybody, 

I have problems doing the same thing. I would like to check if the use is already subcribed before trying to add him to the list. 
Because even if he is already subscribed this code: 
```
$result = $MailChimp->put("lists/$list/members/$id", array(
									'email_address'     => $email,
									'status'            => 'pending',
							));

echo json_encode($result);
```

will be successful and would make it seem that the confirmation email is sent.

I would be very happy if I could get more help.

Julia

**Comment by JohnGrefaldo** [comment]
Hi Julia,

What I can see you're using "PUT" method, which means you're  updating a subscriber ($list/member).
but if you are adding an new subscriber($list/member) using "POST" method there will be a return error msg.

Before you update you should first Get information about members in a list: http://developer.mailchimp.com/documentation/mailchimp/reference/lists/
"Read tab"

Regards,
John
