### ISSUE TITLE
Using Oauth as apikey

### ISSUE THREAD

**Issue by JohnGrefaldo** [drewm/mailchimp-api#129]
Hi Drewn,

It would be great if the $apikey is little bit flexible for the Oauth too.

Kind Regards,
John

**Comment by JohnGrefaldo** [comment]
Hi Drewn,

I've done some changes to the and it work, can you have a look.
I'm not satisfied with my code.

Kind Regards,
John

**Comment by drewm** [comment]
Could you point me to the part of the MailChimp API you're looking to implement?
