### ISSUE TITLE
Unknown error, call getLastResponse() to find out what happened.

### ISSUE THREAD

**Issue by StrangerPings** [drewm/mailchimp-api#130]
When I run this code

```
$list_id = '0961f7f558';

        $result = $MailChimp->post("lists/$list_id/members", [
                        'email_address' => 'myemailgoesinhere@gmail.com',
                        'status'        => 'subscribed',
                    ]);
        if ($MailChimp->success()) {
            print_r($result);   
        } else {
            echo $MailChimp->getLastError();
        }
```

I get Unknown error, call getLastResponse() to find out what happened.

I have ran composer update and nothing seems to fix this issue.

**Comment by andyba45** [comment]
I ran into this when testing on a local machine. I did not have the SSL CA Certificates set up on my machine correctly. Try setting SSL to false.

**Comment by StrangerPings** [comment]
Thankyou very much! I was struggling for hours trying to find the solution 👍
