### ISSUE TITLE
Re-subscriber

### ISSUE THREAD

**Issue by kk12837** [drewm/mailchimp-api#131]
How can I fix it with this error?

Array
(
    [type] => http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/
    [title] => Member Exists
    [status] => 400
    [detail] => keith@doctrinaire.com.au is already a list member. Use PUT to insert or update list members.
    [instance] => 
)

Thanks

Keith

**Comment by Nightbr** [comment]
Hey, use PUT:

Code example:
```
$subscriberHash = $this->mailchimp->subscriberHash($subscriber->getEmail());
$result = $this->mailchimp->put("lists/$listId/members/$subscriberHash",
            array_merge(
                $subscriber->formatMailChimp(),
                ['status' => 'subscribed']
            )
        );
```

**Comment by kk12837** [comment]
Hi Thanks

It works,

How about unsubscribe a use?

Any code example, thanks!

**Comment by Nightbr** [comment]
Same with keyword `unsubscribed`. Look at the [MailChimp documentation](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/) 

```
$subscriberHash = $this->mailchimp->subscriberHash($subscriber->getEmail());
$result = $this->mailchimp->put("lists/$listId/members/$subscriberHash",
            array_merge(
                $subscriber->formatMailChimp(),
                ['status' => 'unsubscribed']
            )
        );
```

**Comment by kk12837** [comment]
Yep, but my email address is still shown as subsriber in mailchimp

any idea?

here is the callback

2016-09-20T07:45:08+00:00 DEBUG (7): Array
(
    [id] => ad8048e630b5003a9e988e2790355595
    [email_address] => kk261188@hotmail.com
    [unique_email_id] => 5e25fb8b24
    [email_type] => html
    [status] => unsubscribed
    [merge_fields] => Array
        (
            [FNAME] => k
            [LNAME] => k
            [POSTCODE] => asd
            [AGEGROUP] => 
            [MOBILE] => 
            [COUNTRY] => AU
            [MMERGE7] => 
            [MMERGE8] => 
            [MMERGE9] => 
            [CGROUP] => 
            [BMONTH] => 
            [MMERGE11] => 
            [MMERGE13] => 
        )

    [interests] => Array
        (
            [1bff07909a] => 
            [47c7c4df85] => 
            [1c3eeb5baa] => 
            [7e24252217] => 
            [d6bc521a3f] => 
            [190b84c0a1] => 
            [e38c7ec15f] => 
            [126db74ed4] => 
            [e42aab9317] => 
            [d40335a4cc] => 
            [474ca26e74] => 
        )

    [stats] => Array
        (
            [avg_open_rate] => 0
            [avg_click_rate] => 0
        )

    [ip_signup] => 
    [timestamp_signup] => 
    [ip_opt] => 58.177.5.214
    [timestamp_opt] => 2016-09-20T07:31:41+00:00
    [member_rating] => 2
    [last_changed] => 2016-09-20T07:45:08+00:00
    [language] => 
    [vip] => 
    [email_client] => 
    [location] => Array
        (
            [latitude] => 22.2831
            [longitude] => 114.213
            [gmtoff] => 8
            [dstoff] => 8
            [country_code] => HK
            [timezone] => Asia/Hong_Kong
        )

    [list_id] => c71e704852
    [_links] => Array
        (
            [0] => Array
                (
                    [rel] => self
                    [href] => https://us2.api.mailchimp.com/3.0/lists/c71e704852/members/ad8048e630b5003a9e988e2790355595
                    [method] => GET
                    [targetSchema] => https://us2.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json
                )

            [1] => Array
                (
                    [rel] => parent
                    [href] => https://us2.api.mailchimp.com/3.0/lists/c71e704852/members
                    [method] => GET
                    [targetSchema] => https://us2.api.mailchimp.com/schema/3.0/Lists/Members/Collection.json
                    [schema] => https://us2.api.mailchimp.com/schema/3.0/CollectionLinks/Lists/Members.json
                )

            [2] => Array
                (
                    [rel] => update
                    [href] => https://us2.api.mailchimp.com/3.0/lists/c71e704852/members/ad8048e630b5003a9e988e2790355595
                    [method] => PATCH
                    [schema] => https://us2.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json
                )

            [3] => Array
                (
                    [rel] => upsert
                    [href] => https://us2.api.mailchimp.com/3.0/lists/c71e704852/members/ad8048e630b5003a9e988e2790355595
                    [method] => PUT
                    [schema] => https://us2.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json
                )

            [4] => Array
                (
                    [rel] => delete
                    [href] => https://us2.api.mailchimp.com/3.0/lists/c71e704852/members/ad8048e630b5003a9e988e2790355595
                    [method] => DELETE
                )

            [5] => Array
                (
                    [rel] => activity
                    [href] => https://us2.api.mailchimp.com/3.0/lists/c71e704852/members/ad8048e630b5003a9e988e2790355595/activity
                    [method] => GET
                    [targetSchema] => https://us2.api.mailchimp.com/schema/3.0/Lists/Members/Activity/Collection.json
                )

            [6] => Array
                (
                    [rel] => goals
                    [href] => https://us2.api.mailchimp.com/3.0/lists/c71e704852/members/ad8048e630b5003a9e988e2790355595/goals
                    [method] => GET
                    [targetSchema] => https://us2.api.mailchimp.com/schema/3.0/Lists/Members/Goals/Collection.json
                )

            [7] => Array
                (
                    [rel] => notes
                    [href] => https://us2.api.mailchimp.com/3.0/lists/c71e704852/members/ad8048e630b5003a9e988e2790355595/notes
                    [method] => GET
                    [targetSchema] => https://us2.api.mailchimp.com/schema/3.0/Lists/Members/Notes/Collection.json
                )

        )

)

**Comment by Nightbr** [comment]
It takes some times to refresh the list view in MailChimp... Refresh and try later...

**Comment by kk12837** [comment]
Ok thanks for your help, I will take a look :)

**Comment by Nightbr** [comment]
If you look at your 'callback'/response, your user is unsubscribed:

```
[id] => ad8048e630b5003a9e988e2790355595
[email_address] => kk261188@hotmail.com
[unique_email_id] => 5e25fb8b24
[email_type] => html
[status] => unsubscribed
```

**Comment by kk12837** [comment]
yes, it is still showing I am a subscriber in the list of mailchimp account.

**Comment by JohnGrefaldo** [comment]
Hi kk12837,

Do mean by "Mailchimp Account" is your mailchimp admin like "**us<dc>.admin.mailchimp.com**" 

If **NO** please disregard my comment.

1. Please check your selection on your Mailchimp account if it's on unsubcriber list:
![image](https://cloud.githubusercontent.com/assets/21042198/18705258/27c9c8ae-8020-11e6-8a40-a8c61ec50a43.png)

2. Also check your Data Center if it is the same as the one your trying to update on your API query.

Kind Regards,
John

**Comment by kk12837** [comment]
thanks it is fixed
