### ISSUE TITLE
update subscriber info

### ISSUE THREAD

**Issue by kk12837** [drewm/mailchimp-api#132]
Hi,

I am trying to update subscriber info in mailchimp

$result = $MailChimp->patch("lists/$list_id/members/$subscriber_hash", array(
        'email_address' => 'keith@doctrinaire.com.au',
        'merge_fields' => array('MERGE9' => 'abc'),
    ));

but it returns

Array
(
    [type] => http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/
    [title] => Method Not Allowed
    [status] => 405
    [detail] => The requested method and resource are not compatible. See the Allow header for this resource's available methods.
    [instance] => 
)

any idea with this?

thanks!

**Comment by drewm** [comment]
It doesn't look like `email_address` is an updatable field from the docs:
http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/

So it could be that. I don't think it's a problem with this library unless you can provide more information about why you think it might be.
