### ISSUE TITLE
Create a campaign

### ISSUE THREAD

**Issue by lfarah** [drewm/mailchimp-api#133]
Regarding #122 

Thank you @webface for asking such a lazy question. I'm new to PHP and I had the same problem and you took the time to find the answer and post it on the issue so other people (like me) could use it. You really had an open source community action.

Thank you @drewm for creating this lib, but you have to be nice to the people who use your library and have questions. I manage libraries with 15 thousand stars and more than 1 thousand weekly downloads and I know sometimes a lot of issues are overwhelming, but remember:

# You should always treat your users really well because without them YOUR LIBRARY IS USELESS

**Comment by drewm** [comment]
Actually, without users my library would be just as useful for my purposes, I'd just not have random entitled strangers having a go at me.

Your message is everything that's bad about open source. Why is it not okay that I make a repo public in case it's useful for someone? Why am I then accountable to nurse every PHP beginner through their development problems? That's not my job. I don't know what logic you're applying that makes you believe I'm morally responsible to help with your questions or even to be nice when you waste my time by raising a bogus issue against the software.

If it wouldn't then break the projects of hundreds of thousands reasonable users, I'd just take this thing offline for the amount of unwarranted abuse it gets me. I certainly will think twice before sharing anything in the future.

**Comment by lfarah** [comment]
@drewm I'm sorry if that's what you think about the Open Source community.

I don't think you are entitled to anything and I agree that you don't need to spend your time on helping every single user that opens an issue, but you owe everybody respect just because we are all human beings and we should respect each other.

If you really wanted to save time with those issues, after @webface posted the answer you could have thanked him and asked him for a pull request with this tutorial on the README, so you and hundreds of thousands of users could easily implement this new functionality.

The Open Source community is all about everybody collaborating to create better tools and products. It's a win-win situation.

If you don't wanna work on this project anymore, you could find someone else that would love to take it over. In the end of the day, you have a good tool and it's definitely not worth it taking it down.
