### ISSUE TITLE
400 Invalid Resource - Products

### ISSUE THREAD

**Issue by Rizsti** [drewm/mailchimp-api#134]
I'm attempting to do some e-commerce work and make a call to /ecommerce/stores/{store_id}/products but I'm getting the following error. The variants field is definitely an array. 

["title"]=> "Invalid Resource",
["status"]=> 400,
["detail"]=> "The resource submitted could not be validated. For field-specific details, see the 'errors' array.",
["instance"]=> "",
["errors"]=> array(1) {
  [0]=>  array(2) {
       ["field"]=>"variants",
    ["message"]=>"Schema describes array, object found instead"
  }
}

**Comment by ildar-aim** [comment]
@Rizsti 

Dear Andrea, 

How have you fixed the problem ?

Thank you.
