### ISSUE TITLE
search-members helper works in terminal (cURL) but not with this wrapper

### ISSUE THREAD

**Issue by edeoldi** [drewm/mailchimp-api#135]
Hey there,

first of all, thank you for all the great work! :-)

I am having a hard time getting the [search-members helper](http://developer.mailchimp.com/documentation/mailchimp/reference/search-members/#read-get_search_members) to work with this wrapper. 

Example:

> $result = $MailChimp->get("search-members?query=$search_string");
> 
> print_r($result);

Output:

> Array
> (
> [exact_matches] => Array
> (
> [members] => Array
> (
> )
> 
> [total_items] => 0
> )
> 
> [full_search] => Array
> (
> [members] => Array
> (
> )
> 
> [total_items] => 0
> )
> 
> [_links] => Array
> (
> [0] => Array
> (
> [rel] => self
> [href] => https://us12.api.mailchimp.com/3.0/search-members
> [method] => GET
> [targetSchema] => https://us12.api.mailchimp.com/schema/3.0/SearchMembers/Collection.json
> )
> 
> [1] => Array
> (
> [rel] => parent
> [href] => https://us12.api.mailchimp.com/3.0/
> [method] => GET
> [targetSchema] => https://us12.api.mailchimp.com/schema/3.0/Root.json
> )
> 
> )
> 
> )

It does however work with a cURL GET request:

> curl -H "Authorization: apikey ***" https://us12.api.mailchimp.com/3.0/search-members?query=$search_string

Any ideas? Thank you in advance!

**Comment by drewm** [comment]
Try this:

```php
$result = $MailChimp->get("search-members", ['query' => $search_string]);
print_r($result);
```
