### ISSUE TITLE
$MailChimp->get('lists') returns false.

### ISSUE THREAD

**Issue by otjutt** [drewm/mailchimp-api#136]
```
require_once dirname(__FILE__) . "/path-to/MailChimp.php";
use \DrewM\MailChimp\MailChimp;
$MailChimp = new MailChimp('myapikey');
$lists = $MailChimp->get('lists');
var_dump($lists);
```

I can't understand why this code is always returning false. It seems to be working a month ago. I've tried this code by making an new API key too.

PHP 5.5

**Comment by terrymun** [comment]
Check yours server error and/or access logs. Any strange messages when you execute the PHP file? There is a possibility that cURL is not being configured properly or that certificates are not being set up properly, causing cURL to fail silently.

**Comment by nkrastev** [comment]
otjutt, are testing on localhost? I've the same error, upload it and it is working.

**Comment by otjutt** [comment]
> otjutt, are you testing on localhost? I've the same error, upload it and it is working.

@nkrastev Yes, I'm testing on WAMP. It was working fine on my local vagrant box though. I didn't get time to delve deeper into it.
