### ISSUE TITLE
Parse error:

### ISSUE THREAD

**Issue by paulsimonrough** [drewm/mailchimp-api#138]
Might be me being daft but I keep getting a parse error PHP 5.3.29

With the following code:

$result = $MailChimp->post("lists/$list_id/members", [
                'email_address' => 'davy@example.com',
                'status'        => 'subscribed',
            ]);

print_r($result);

Error returned:

Parse error: syntax error, unexpected '['

**Comment by terrymun** [comment]
The array shorthand, `[...]` instead of `array(...)`, is only supported in [PHP5.4 and above](http://php.net/manual/en/migration54.new-features.php).

**Comment by paulsimonrough** [comment]
How much of this is in PHP 5.4? the description says its PHP 5.3

Sorry to be a pain but how should the following code be?

$result = $MailChimp->post("lists/$list_id/members", [
'email_address' => 'davy@example.com',
'status' => 'subscribed',
]);

Thanks, Paul.

**Comment by terrymun** [comment]
Instead of using `[...]` in your code revert to using `array()`. The base code I suppose is PHP 5.3 compatible. The examples provided are not.

**Comment by paulsimonrough** [comment]
$result = $MailChimp->post("lists/$list_id/members", array(
'email_address' => 'davy@example.com',
'status' => 'subscribed',
));

This works thanks.
