### ISSUE TITLE
'status'        => 'subscribed',

### ISSUE THREAD

**Issue by paulsimonrough** [drewm/mailchimp-api#139]
Might not be an issue but is there another status instead of 'subcribed' like 'pending' or similar?

The reason I ask is, it subscribes them automatically and no opt in confirmation email is sent out to the subscriber even though they appear in the list.

**Comment by alejandro-fiore** [comment]
According to MailChimp documentation, the possible values for "status" are `subscribed,` `unsubscribed`, `cleaned` and `pending`.
[http://developer.mailchimp.com/documentation/mailchimp/reference/lists/#create-post_lists_list_id](url)
look for the option "Show properties" in members parameter.

**Comment by paulsimonrough** [comment]
Cheers, that worked! I changed the code to pending:

$result = $MailChimp->post("lists/$list_id/members", array(
                'email_address' => 'something@email.com',
                'status'        => 'pending',
            ));

And mail chimp sent out a confirm email address automatically.

Thanks.
