### ISSUE TITLE
Mailchimp - An email address must contain a single @

### ISSUE THREAD

**Issue by hansendennis** [drewm/mailchimp-api#140]
Hi

when trying to push a lead to our mailchimp integration I can see this error message in the log.

[2016-10-26 20:52:19] mautic.ERROR: INTEGRATION ERROR: Mailchimp - An email address must contain a single @ [] []

we are running 2.2 of mailchimp and its api version 3 thats been used.

anyone with the same problem?

Dennis

**Comment by drewm** [comment]
This sounds like an API usage issue.
