### ISSUE TITLE
Sending campaigns

### ISSUE THREAD

**Issue by HornKild** [drewm/mailchimp-api#141]
Hello, 

Is there a possibility to send campaign with this MailChimp wrapper ? I'm looking for a way to periodicaly send campaigns to my members (every Monday at a specific time).

Thank you,

**Comment by HornKild** [comment]
Not a coding expert but I think a call like this should work :) 

`$result = $MailChimp->put("campaigns/$campaign_id/content", [
                'url' => 'http://mywebsite.com/campaign-content.html',
            ]);
`

http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/content/#edit-put_campaigns_campaign_id_content

My objective is to send a campaign periodically from a URL, where content of the URL is updated.

**Comment by drzraf** [comment]
> My objective is to send a campaign periodically from a URL, where
> content of the URL is updated.

I used to do it (using API 1.3 though).
Have a look at RSS campaign which provides the same "regularity"
feature. It may fit your needs.

**Comment by HornKild** [comment]
> Have a look at RSS campaign which provides the same "regularity"
Thanks Raphaël, unfortunnatly RSS is a public feed and my campaign are for members only.

Florent
