### ISSUE TITLE
Batch: Error when using get member with fields/exclude_fields

### ISSUE THREAD

**Issue by Tuhljin** [drewm/mailchimp-api#142]
When I include either fields or exclude_fields parameters in a batched attempt to ["Get information about a specific list member"](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#read-get_lists_list_id_members_subscriber_hash) ("lists/[LIST_ID]/members/[EMAIL_HASH]"), I get this error back from MailChimp: "Schema describes object, string found instead"

The context of that error message, returned from $Batch->execute():

```
array (
  'batch_id' => false,
  'ret' =>
  array (
    'type' => 'http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/',
    'title' => 'Invalid Resource',
    'status' => 400,
    'detail' => 'The resource submitted could not be validated. For field-specific details, see the \'errors\' array.',
    'instance' => '',
    'errors' =>
    array (
      0 =>
      array (
        'field' => 'operations.item:0.params',
        'message' => 'Schema describes object, string found instead',
      ),
    ),
  ),
)
```

If I use the same code but with a normal query instead of a batch, it works as expected. Likewise, if I use the same code but omit the fields/exclude_fields parameters, then it works as expected even as a batch.

Example code:  (I've trimmed it down and used global variables to keep it simple for our purposes, here.)

```
$MC = new \DrewM\MailChimp\MailChimp( $MCKEY );
$Batch = $MC->new_batch();
foreach ($emails as $e) {
	$key = "abc:def=$e";
	$hash = $MC->subscriberHash($e);

	// This way works but the return is larger than ought to be necessary, since it includes a lot of fields we don't want:
	//$Batch->get($key, 'lists/' . $LISTID . '/members/' . $hash);
	// There's a "fields" parameter that, per the documentation, is what we want... but using it makes the whole thing fail.

	$arr = [
		'fields'	=> 'email_address,status',
	];

	// The non-batch way works fine:
	print_r( $MC->get('lists/' . $LISTID . '/members/' . $hash, $arr, $TIMEOUT) );

	// The real call. MailChimp gives an error once the batch is executed, below.
	$Batch->get($key, 'lists/' . $LISTID . '/members/' . $hash, $arr);
}
$batch_data = $Batch->execute();
print_r($batch_data);
// Gives output pasted above.
```

**Comment by drewm** [comment]
This could be a MailChimp API issue. Have you asked them about it?

**Comment by drzraf** [comment]
```
{"operations" : [{"method":"GET","path":"lists/xxx/members/856138c2yyyyyyyyyyyyyyy","params":"fields":"id,status,timestamp_opt"}}]}
```
``$ curl --user blah:$MAILCHIMP_API_KEY --request POST --url 'https://us1.api.mailchimp.com/3.0/batches' --header 'content-type: application/json' --data @requests.json``

Batch job is stuck so I'd say that it would be no surprise if it'd be *yet* another MailChimp API bug
