### ISSUE TITLE
Update Merge fields with post (batch upload)

### ISSUE THREAD

**Issue by viu-simon** [drewm/mailchimp-api#143]
Hello, thanks for this cool wrapper. It's really helpfull. Sadly i face an issue by batch updating data using POST. 
I did a test, by first uploads only email addresses. In a second run i added Name, and other data, but it doesn't updatet the records on mailchimp. I tried also by using PATCH instead of POST. 

If i deleted all records in Mailchimp and upload them with all data, it works perfect. Only updating is not working.

What could be the issue?

**Comment by viu-simon** [comment]
Ok, i figured out, that put is not allowed for batch. Post is needed to create a new record, put for update or create records. In your comments you mixed up. 
When i update records, i got the error msg i should use put. When i use put i got the message that this is not allowed. Does anybody knows the solution, to update recrods by batch?

this is not working:
`        foreach ($customers as $key => $c){
            $batch->put("op$key", "lists/$list_id/members", [
                'email_address' => $c['email'],
                'status'        => 'subscribed',
                'merge_fields' => array(
                    'FNAME' => $c['firstname'],
                    'LNAME' => $c['lastname'],
                    'BDAY' => $c['birthday'],
                    'SIGNUP' => $c['date_signup'],
                    )
            ]);
        }`

**Comment by drewm** [comment]
> In your comments you mixed up. 

Is that directed at me? I'm not sure what issue you're seeing.

**Comment by viu-simon** [comment]
Your comments are wrong. You mixed up Post and Put :-)

Your File: mailchimp.php row 141
`    
    /**
     * Make an HTTP POST request - for creating and updating items
     * @param   string $method URL of the API request method
     * @param   array $args Assoc array of arguments (usually your data)
     * @param   int $timeout Timeout limit for request in seconds
     * @return  array|false   Assoc array of API response, decoded from JSON
     */
    public function post($method, $args = array(), $timeout = 10)
    {
        return $this->makeRequest('post', $method, $args, $timeout);
    }
    /**
     * Make an HTTP PUT request - for creating new items
     * @param   string $method URL of the API request method
     * @param   array $args Assoc array of arguments (usually your data)
     * @param   int $timeout Timeout limit for request in seconds
     * @return  array|false   Assoc array of API response, decoded from JSON
     */
    public function put($method, $args = array(), $timeout = 10)
    {
        return $this->makeRequest('put', $method, $args, $timeout);
    }`

From the Mailchimp Documentation:

> POST
Use a POST request to create new resources. For example, make a POST request to a collection endpoint (like /lists) where the body of your request JSON is a new list.
PATCH
Make a PATCH request to update a resource. With PATCH requests, you only need to provide the data you want to change.
PUT
Use a PUT request to create or update a resource. This is most useful for syncing subscriber data.


I tried to use PUT in a batch, but i got an error. Only Post is possible...

Hope its more clear what i want to say :-)

**Comment by dominikhenn** [comment]
Hi, this is not a bug. For PUT you have to add the 'subscriber_hash' to the $method parameter:

`foreach ($customers as $key => $c){ $batch->put("op$key", "lists/$list_id/members/" . $MailChimp->subscriberHash($c['email']), [ 'email_address' => $c['email'], 'status' => 'subscribed', 'merge_fields' => array( 'FNAME' => $c['firstname'], 'LNAME' => $c['lastname'], 'BDAY' => $c['birthday'], 'SIGNUP' => $c['date_signup'], ) ]); }`

**Comment by petemolinero** [comment]
@drewm While it's a nit-picky thing, he OP was actually correct here about your comments. Your comments read:

`Make an HTTP POST request - for creating and updating items`

and:

`Make an HTTP PUT request - for creating new items`

In actuality, POST is only for creating, and PUT is for creating and updating. They're backwards.

**Comment by drewm** [comment]
What comments are you referring to?

**Comment by petemolinero** [comment]
https://github.com/drewm/mailchimp-api/blob/a6519cafba509e754e748d93f3532ad7f3aa515a/src/MailChimp.php#L177

And 

https://github.com/drewm/mailchimp-api/blob/a6519cafba509e754e748d93f3532ad7f3aa515a/src/MailChimp.php#L191

**Comment by drewm** [comment]
I mean, yeah, sure. Feel free to send a PR!
