### ISSUE TITLE
Timeout should be obvious.

### ISSUE THREAD

**Issue by Insti** [drewm/mailchimp-api#144]
When a request times out the `getLastError()` is:
```
Unknown error, call getLastResponse() to find out what happened.
```
But `getLastResponse()` does not really make it clear what the error was and the `$timeout` value is not present in the output of `getLastResponse()` which adds to the difficulty in determining that a timeout occurred.

**Proposal**

If the curl request times out, the error message should be something more useful like:
`"Request timed out after $timeout seconds."`

This can easily be detected because the array returned by `curl_getinfo($ch)`
contains a `total_time` element which is greater than the `$timeout` value.

**Comment by drewm** [comment]
Sure, I'd be happy to accept a pull request for that feature.

**Comment by hvt** [comment]
My PR #163 helps by detecting timeouts (although not in the way described here)...
