### ISSUE TITLE
Webhook ... must be an instance of DrewM\MailChimp\callable, instance of Closure given

### ISSUE THREAD

**Issue by dimitrijev** [drewm/mailchimp-api#146]
Hi,
there is a error when using webhook subscribe method with PHP version 5.3.3. 

Catchable fatal error: Argument 2 passed to DrewM\MailChimp\Webhook::subscribe() must be an instance of DrewM\MailChimp\callable, instance of Closure given

Thanks

**Comment by longwave** [comment]
`callable` typehint was only added in PHP 5.4 so minimum version should probably be raised.

**Comment by drewm** [comment]
I'll add a note to the Readme - thanks.
