### ISSUE TITLE
request_successful = false / Unknown error

### ISSUE THREAD

**Issue by impressivewebs** [drewm/mailchimp-api#147]
Hey @drewm, thanks for this script, it's certainly helped. Up until now I've had no problems using the script to display subscriber counts with the old version, compatible with MailChimp's pre-v3 API. However, I cannot get the new version (for MailChimp 3) to work.

After I include MailChimp.php, I'm doing the following:

    use \DrewM\MailChimp\MailChimp;
    $MailChimp = new MailChimp('xxxxxxxxxxxxxxxxxxxxxxxxxx-us5');
    $result = $MailChimp->get('lists');

If I try to echo/print the `$result` variable, I get nothing. If I `var_dump` it, I get `bool(false)`. If I `var_dump($MailChimp)`, I get the following:

> object(DrewM\MailChimp\MailChimp)#1 (7) { ["api_key":"DrewM\MailChimp\MailChimp":private]=> string(36) "xxxxxxxxxxxxxxxxxxxxxxxxxx-us5" ["api_endpoint":"DrewM\MailChimp\MailChimp":private]=> string(33) "https://us5.api.mailchimp.com/3.0" ["verify_ssl"]=> bool(true) ["request_successful":"DrewM\MailChimp\MailChimp":private]=> bool(false) ["last_error":"DrewM\MailChimp\MailChimp":private]=> string(64) "Unknown error, call getLastResponse() to find out what happened." ["last_response":"DrewM\MailChimp\MailChimp":private]=> array(2) { ["headers"]=> array(20) { ["url"]=> string(40) "https://us5.api.mailchimp.com/3.0/lists?" ["content_type"]=> NULL ["http_code"]=> int(0) ["header_size"]=> int(0) ["request_size"]=> int(0) ["filetime"]=> int(-1) ["ssl_verify_result"]=> int(0) ["redirect_count"]=> int(0) ["total_time"]=> float(0) ["namelookup_time"]=> float(0) ["connect_time"]=> float(0.015) ["pretransfer_time"]=> float(0) ["size_upload"]=> float(0) ["size_download"]=> float(0) ["speed_download"]=> float(0) ["speed_upload"]=> float(0) ["download_content_length"]=> float(-1) ["upload_content_length"]=> float(-1) ["starttransfer_time"]=> float(0) ["redirect_time"]=> float(0) } ["body"]=> bool(false) } ["last_request":"DrewM\MailChimp\MailChimp":private]=> array(5) { ["method"]=> string(3) "get" ["path"]=> string(5) "lists" ["url"]=> string(39) "https://us5.api.mailchimp.com/3.0/lists" ["body"]=> string(0) "" ["timeout"]=> int(10) } }

And of course, note that I've removed my API key in the examples above. The API key is correct in my code, and I even generated a new one just to ensure I had it right.

Ultimately, I had to settle [for this solution](https://rudrastyh.com/mailchimp-api/get-lists.html), which works perfectly. I have no idea what's preventing your script from working in my case. The PHP version I'm testing on is 5.3.1 and I've enabled cURL in php.ini, which I believe is required.

Any thoughts on what's going wrong?

**Comment by starflower** [comment]
Same here

**Comment by walshy002000** [comment]
Same issue here.

**Comment by Falcikas** [comment]
For me setting the : 
`public $verify_ssl = false;`

in MailChimp.php worked I have no SSL sertificate set on my local machine.

**Comment by drewm** [comment]
> Unknown error, call getLastResponse() to find out what happened.

Did you call `getLastResponse()` to find out what happened, @impressivewebs?

**Comment by impressivewebs** [comment]
@drewm I thought I tried it, but I don't really understand what I'm supposed to read when I use that. I didn't get anything out of that to help me debug it, if that's what you're asking. If you want, I can try again and see what it says. But IIRC, it didn't help me.

**Comment by impressivewebs** [comment]
@drewm Ok, if I do:

    var_dump($MailChimp->getLastResponse());

I get:

    array(2) { ["headers"]=> array(20) { ["url"]=> string(40) "https://us5.api.mailchimp.com/3.0/lists?" ["content_type"]=> NULL ["http_code"]=> int(0) ["header_size"]=> int(0) ["request_size"]=> int(0) ["filetime"]=> int(-1) ["ssl_verify_result"]=> int(0) ["redirect_count"]=> int(0) ["total_time"]=> float(0) ["namelookup_time"]=> float(0) ["connect_time"]=> float(0.032) ["pretransfer_time"]=> float(0) ["size_upload"]=> float(0) ["size_download"]=> float(0) ["speed_download"]=> float(0) ["speed_upload"]=> float(0) ["download_content_length"]=> float(-1) ["upload_content_length"]=> float(-1) ["starttransfer_time"]=> float(0) ["redirect_time"]=> float(0) } ["body"]=> bool(false) }

I have no idea what I'm looking for in there.

**Comment by drewm** [comment]
That looks like an SSL problem with your server:

```["ssl_verify_result"]=> int(0)```

**Comment by impressivewebs** [comment]
Oh... well, the server I'm testing on is my local machine, so that would explain that. Another user in this thread mentioned setting `public $verify_ssl = false;`, so I guess that's what's needed? Forgot to try that. Is it unsafe to use the script in a non-SSL environment or something?

**Comment by impressivewebs** [comment]
Yeah, I just tried it and it seems to work fine now. I guess that's solved, but I suppose it would be good if the docs explained the problem, or else provided instructions to set that to false if necessary.

**Comment by drewm** [comment]
They do: https://github.com/drewm/mailchimp-api#troubleshooting

**Comment by impressivewebs** [comment]
@drewm Ah ok... Sorry, my bad. I guess I hadn't read the docs since the update. :( Thanks.

**Comment by lhviet** [comment]
I set the verify_ssl to false and it works as normal (on localhost)
`$MailChimp->verify_ssl = false;`

**Comment by xeagle2** [comment]
Why the error related to ssl is not returned by getLastError? It looks like another issue. 

The error should be clearly returned as well as other errors. Taking a look at getLastResponse is more technical and in some cases doesn't bring the clarity unfortunately in order to understand the cause as for example the cause with SSL.

**Comment by bryan3561** [comment]
https://github.com/bryan3561/mailchimp-api
this is correct


or changue for this code:
https://github.com/drewm/mailchimp-api/commit/d2691e57fb7b45ba475a09254e058d851f322c30
