### ISSUE TITLE
Mailchimp API - language setting/argument

### ISSUE THREAD

**Issue by dev4q1** [drewm/mailchimp-api#148]
Hi,

today I ran into an issue regarding the language parameter when adding a member to a list. By setting the language parameter with the language code the subscriber gets the language set in the subscriber list (Mailchimp admin interface). So far that works.

However if the admin has set up an opt-in confirmation mail then this mail sent to the subscriber will be in the default language set in to "Sign-up form" settings, not in the language associated with the subscriber.

The issue is that via mailchimp api the language of the opt-in messages can't be set (http://stackoverflow.com/a/22072474). However as stated by Brett in the post there's a workaround by checking the "Auto-translate" option in "Sign-up Form" -> "Translate-it". This would cause Mailchimp to get the correct language by "faking" the browser language.

To achieve this I made a small change in the function:

    private function makeRequest($http_verb, $method, $args = array(), $timeout = 10) 
    {
        ...

        $httpHeader = array(
            "Accept: application/vnd.api+json",
            "Content-Type: application/vnd.api+json",
            "Authorization: apikey " . $this->api_key
        );

        if (isset($args["language"])) {
            $httpHeader[] = "Accept-Language: " . $args["language"];
        }

        ...

        curl_setopt($ch, CURLOPT_HTTPHEADER, $httpHeader);

        ...

    }

Would you be interested in taking over this small change?

Best Regards,
Quan

**Comment by drewm** [comment]
Yes, I'd be interested in a PR for that - good idea.

**Comment by slavielle** [comment]
Looks like dev4q1 won't make the PR :) I'll do ... we need this update.

**Comment by slavielle** [comment]
I was expecting this would also allow to define the language for response title property and error message (using MailChimp::getLastError) but it seems not working. Those strings remain EN whatever.

**Comment by drewm** [comment]
I think the error message is aimed at the developer rather than the user!

**Comment by slavielle** [comment]
Yes and no. One's sometimes want to provide details about the error to a localized end user. Beside In case of error a very hi-level cause or this error is returned in the title property of the response. It would be great at least this would be translated. But it's not on your lib ;)
