### ISSUE TITLE
Getting Empty Response when trying to request all lists

### ISSUE THREAD

**Issue by Nukro** [drewm/mailchimp-api#153]
Hi Guys

I get sometimes an empty response when i am trying to request all lists. But this only happens in one of the two accounts I'm using. One account has 79 Lists and the other has 139 lists (its happening here). I am using the wrapper inside an module I wrote for the CMS we are using at our company. All other features are working great. I also contacted the support about it and they said It could be a timeout issue. So I set a set_time_limit inside my module but with no effect. Do you have encountered this problem? How can I solve this or better said whats the problem? Is it really a timeout? Because the MailChimp Support said: 

> I am seeing that that last GET /lists call included the fields, and is showing a response body, so it's likely that this is due to the timeout being set to low or something peculiar with the way you're viewing responses. 
> 
> Try extending your timeout first, and if that doesn't solve the issue let us know and we can go from there.

**Comment by Insti** [comment]
@Nukro you're probably getting a timeout from the http request, not the php script.
You're probably doing something like: `$result = $MailChimp->get('lists');`

Instead you need to do something like: 
```
$args = array();
$timeout = 60; // Timeout in seconds (default is 10).
$result = $MailChimp->get('lists', $args, $timeout);
```

**Comment by harshek** [comment]
hello @Nukro I tried to increase the timeout to 300 but still facing same error no list get displayed.
So what is the issue please let us know?
Also what we can pass in $args?
Is it possible we can get the list of function for our integration?

**Comment by harshek** [comment]
One more Info I want to Provide, I am working on localhost, so it will support Localhost?
Or its need live server and is it also required SSL enabled?

**Comment by drewm** [comment]
@Nukro did you get to the bottom of this?

**Comment by Nukro** [comment]
@drewm increasing the timeout solved it. Thanks for asking.

**Comment by harshek** [comment]
Well code will not work on localhost. So thank you for the help when I tested it on live server it worked perfectly.
Thank you once again.
