### ISSUE TITLE
Get Interest ID Possible?

### ISSUE THREAD

**Issue by casbboy** [drewm/mailchimp-api#154]
I know you can do a query like this:

$result = $MailChimp->get("lists/$list_id/interest-categories/$interest_category/interests/");

To get all interests in an interest category. But is it possible to see if a particular Interest already exists (by name) and, if it does, just return that Interest ID?

something like
$interest_hash = $MailChimp->subscriberHash('Video Games');
$result = $MailChimp->get("lists/$list_id/interest-categories/$interest_category/interests/$interest_hash");

Something like that possible?

Cheers!
Ryan

**Comment by drewm** [comment]
That sounds like a question to put to MailChimp - I think it relates to the API itself rather that this library.
