### ISSUE TITLE
How to use Batch Unsubscribe?

### ISSUE THREAD

**Issue by harshek** [drewm/mailchimp-api#157]
I checked your tutorials, There is option to add Subscribers in Batch, but there is not option to unsubscribe users in batch?
Is there any option to unsubscribe users in batches or bulk?
Because delete function will delete 1/1 and it will take time.
Also one more query, to add first_name, last_name we need to use function patch for that. is there any method to add users directly through batch function?

**Comment by drewm** [comment]
This library doesn't implement any of the API's functionality - you need to find the methods you want to execute in the MailChimp docs and then this library should enable you to execute them.

If there's something in the MailChimp API that you could do with a raw cURL request but can't do with this library, please feel free to raise an issue with the specifics of that case. Thanks!
