### ISSUE TITLE
How to get Campaign Open Member Report

### ISSUE THREAD

**Issue by harshek** [drewm/mailchimp-api#158]
Hello drewm,

I need the detail for the users who open the campaign and the count too, is there any method in the existing code for it?

**Comment by drewm** [comment]
This library doesn't implement any of the API's functionality - you need to find the methods you want to execute in the MailChimp docs and then this library should enable you to execute them.

If there's something in the MailChimp API that you could do with a raw cURL request but can't do with this library, please feel free to raise an issue with the specifics of that case. Thanks!
