### ISSUE TITLE
Error codes for some useful request statuses is missing

### ISSUE THREAD

**Issue by camohub** [drewm/mailchimp-api#161]
Hi, 
If I make mailchimp->post() request to add new subscriber it fails if user already exists on mailchimp server. Or if call mailchimp->patch() to update user fails if there is no user with required email. In this case I would like to have error code which exactly identifies what happens on server. 
If user does not exist I would like to test it and send a create request. Otherwise if user already exists I would like to test it and make update for e.g. status, fname, .....

Now there is mailChimp->getLastResponse()['body'] which contents title with error message. But title can change in future so it is not  reliable identifier of response status. 

I dont know mailchimp native API and dont know if mailchimp sends reliable error codes in response.
Can I hope in this? THX.

PS: Maybe something like createOrUpdate() will be helpfull.

**Comment by terrymun** [comment]
It says quite clearly that you have to [use the PUT method when adding or updating a subscriber](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-put_lists_list_id_members_subscriber_hash), that is probably why your POST requests are rejected or fail to be executed. 

As @drewm has mentioned before, the Mailchimp API he has written serves as a general and easy-to-use wrapper for interfacing with the actual Mailchimp API. A createOrUpdate() method is simply an alias of the PUT method above and actually does not add any value to the plugin, in my honest opinion. 

I encourage you to read up the Mailchimp V3 API: it is actually very well written and contains a wealth of information and examples.

**Comment by camohub** [comment]
Yes you are right. I have it.
