### ISSUE TITLE
Shorthand Ternary Operator Doesn't Work with < PHP 5.3

### ISSUE THREAD

**Issue by grimmdude** [drewm/mailchimp-api#162]
The shorthand ternary operator in MailChimp::getLastError() causes a fatal error in < PHP 5.3.  Why not change to support < PHP 5.3?

-Garrett

**Comment by terrymun** [comment]
Well, PHP 5.2 was released more than 6 years ago. I have a feeling that @drewm written Mailchimp API to support 5.3+ for reasons that are quite important towards a clean, verbose code, such as nesting of thrown exceptions and namespaces.

p/s: [It isn't that difficult to migrate your codebase](http://php.net/migration53) over to v5.3 anyway.

**Comment by grimmdude** [comment]
Thanks for your reply.  Reason I ask is because I'm using this library in a distributed Wordpress plugin, so support for < PHP 5.3 is necessary.  Sounds like using a different library might be my best option in this case.

**Comment by terrymun** [comment]
You can always enforce a minimum PHP version, using [a sample snippet](http://wordpress.stackexchange.com/a/76008) from the WP StackExchange answer: 

```php
<?php
if ( version_compare( PHP_VERSION, '5.1', '<' ) )
{
    exit( sprintf( 'Foo requires PHP 5.1 or higher. You’re still on %s.', PHP_VERSION ) );
}
?>
```

PHP5.2 has not been actively developed for a few years now, and attempting to preserve reverse compatibility for archaic versions only encourages sysadmins to not upgrade their PHP installations.

**Comment by drewm** [comment]
I think we're already pretty generous in accommodating versions of PHP as old as 5.3. It is not a goal to support versions older than this, as it would require removing namespaces etc, which is a bit barbaric.

**Comment by grimmdude** [comment]
Welcome to the world of Wordpress.  Ok thanks everyone

**Comment by topdown** [comment]
Note: WordPress is no longer requiring support for PHP 5.2.*

**Comment by butlerblog** [comment]
I know this is a slightly older thread, but it's not marked as closed so I'll add some additional information for @grimmdude.

PHP 5.2.x support is not required for plugins and has not been for some time.  Yes, WP "officially" runs on < 5.3, but it **_will_** be dropping EOL'd versions of PHP in the foreseeable future.  It's a done deal, it just requires working through the semantics of the change.  For plugins, there will be a compatibility checker for PHP much like the WP version compatibility checker now.  That will make it easier for developers to identify PHP requirements for their plugin.

I don't want to drift off topic too much and you can follow the PHP meeting recaps in the [Core development](https://make.wordpress.org/core/) if you want more info.  The bottom line is that changing to support PHP < 5.3 is moving backwards, is not safe from a security standpoint, and is no longer necessary from a WP standpoint; so this ticket should be closed.
