### ISSUE TITLE
lots of warnings about function declarations

### ISSUE THREAD

**Issue by RobertP3469** [drewm/mailchimp-api#166]
Backtrace from warning 'Declaration of Campaigns_Feedback::POST() should be compatible with Campaigns::POST($type, $settings = Array, $optional_parameters = Array)' at \mailchimp-api-3-0-php\campaigns\campaignsFeedback.php 64:

Backtrace from warning 'Declaration of Campaigns_Feedback::PATCH() should be compatible with Campaigns::PATCH($params = Array)' at \mailchimp-api-3-0-php\campaigns\campaignsFeedback.php 64:

Backtrace from warning 'Declaration of Ecommerce_Customers::POST() should be compatible with Ecommerce_Stores::POST($storeid, $listid, $name, $currencycode, $optional_parameters = Array)' at \mailchimp-api-3-0-php\ecommerceStores\ecommerceStoresCustomers.php 96:

Backtrace from warning 'Declaration of Ecommerce_Store_Carts::POST() should be compatible with Ecommerce_Stores::POST($storeid, $listid, $name, $currencycode, $optional_parameters = Array)' at \mailchimp-api-3-0-php\ecommerceStores\carts\ecommerceStoresCartsRoot.php 94:

Backtrace from warning 'Declaration of Ecommerce_Stores_Cart_Lines::POST() should be compatible with Ecommerce_Store_Carts::POST($cartid, $customer, $currency_code, $order_total, $lines, $optional_parameters = Array)' at \mailchimp-api-3-0-php\ecommerceStores\carts\ecommerceStoresCartLines.php 71:

Backtrace from warning 'Declaration of Ecommerce_Stores_Orders::POST() should be compatible with Ecommerce_Stores::POST($storeid, $listid, $name, $currencycode, $optional_parameters = Array)' at \mailchimp-api-3-0-php\ecommerceStores\orders\ecommerceStoresOrdersRoot.php 99:

Backtrace from warning 'Declaration of Ecommerce_Stores_Order_Lines::POST() should be compatible with Ecommerce_Stores_Orders::POST($orderid, $customer, $currency_code, $order_total, $lines, $optional_parameters = Array)' at \mailchimp-api-3-0-php\ecommerceStores\orders\ecommerceStoresOrderLines.php 72:

Backtrace from warning 'Declaration of Ecommerce_Stores_Products::POST() should be compatible with Ecommerce_Stores::POST($storeid, $listid, $name, $currencycode, $optional_parameters = Array)' at \mailchimp-api-3-0-php\ecommerceStores\products\ecommerceStoresProductsRoot.php 92:

Backtrace from warning 'Declaration of Ecommerce_Stores_Products_Variants::POST() should be compatible with Ecommerce_Stores_Products::POST($productid, $title, $variants = Array, $optional_parameters = Array)' at \mailchimp-api-3-0-php\ecommerceStores\products\ecommerStoresProductVariants.php 91:

Backtrace from warning 'Declaration of Lists_Merge_Fields::POST() should be compatible with Lists::POST($name, $reminder, $emailtype, $company, $address_street, $address_street2, $address_city, $address_state, $address_zip, $country, $from_name, $from_email, $subject, $language, $optional_parameters = Array)' at \mailchimp-api-3-0-php\lists\listsMergeFields.php 68:

Backtrace from warning 'Declaration of Lists_Merge_Fields::PATCH() should be compatible with Lists::PATCH($patch_params = NULL)' at \mailchimp-api-3-0-php\lists\listsMergeFields.php 68:

Backtrace from warning 'Declaration of Lists_Signup_Forms::POST() should be compatible with Lists::POST($name, $reminder, $emailtype, $company, $address_street, $address_street2, $address_city, $address_state, $address_zip, $country, $from_name, $from_email, $subject, $language, $optional_parameters = Array)' at \mailchimp-api-3-0-php\lists\listsSignupForms.php 40:

Backtrace from warning 'Declaration of Lists_Webhooks::POST() should be compatible with Lists::POST($name, $reminder, $emailtype, $company, $address_street, $address_street2, $address_city, $address_state, $address_zip, $country, $from_name, $from_email, $subject, $language, $optional_parameters = Array)' at \mailchimp-api-3-0-php\lists\listsWebhooks.php 59:

Backtrace from warning 'Declaration of Lists_Interest_Categories::POST() should be compatible with Lists::POST($name, $reminder, $emailtype, $company, $address_street, $address_street2, $address_city, $address_state, $address_zip, $country, $from_name, $from_email, $subject, $language, $optional_parameters = Array)' at \mailchimp-api-3-0-php\lists\interestCategories\listsInterestsCategoriesRoot.php 82:

Backtrace from warning 'Declaration of Lists_Interest_Categories::PATCH() should be compatible with Lists::PATCH($patch_params = NULL)' at \mailchimp-api-3-0-php\lists\interestCategories\listsInterestsCategoriesRoot.php 82:

Backtrace from warning 'Declaration of Lists_Interests_Categories_Interest::POST() should be compatible with Lists_Interest_Categories::POST($title, $type)' at \mailchimp-api-3-0-php\lists\interestCategories\listsInterestsCategroiesInterests.php 66:

Backtrace from warning 'Declaration of Lists_Interests_Categories_Interest::PATCH() should be compatible with Lists_Interest_Categories::PATCH($title, $type)' at \mailchimp-api-3-0-php\lists\interestCategories\listsInterestsCategroiesInterests.php 66:

Backtrace from warning 'Declaration of Lists_Members::POST() should be compatible with Lists::POST($name, $reminder, $emailtype, $company, $address_street, $address_street2, $address_city, $address_state, $address_zip, $country, $from_name, $from_email, $subject, $language, $optional_parameters = Array)' at \mailchimp-api-3-0-php\lists\members\listsMembersRoot.php 129:

Backtrace from warning 'Declaration of Lists_Members_Member_Notes::POST() should be compatible with Lists_Members::POST($status, $emailaddress, $optional_parameters = Array)' at \mailchimp-api-3-0-php\lists\members\listsMembersMemberNotes.php 67:

Backtrace from warning 'Declaration of Lists_Members_Member_Notes::PATCH() should be compatible with Lists_Members::PATCH($patch_parameters = Array)' at \mailchimp-api-3-0-php\lists\members\listsMembersMemberNotes.php 67:

Backtrace from warning 'Declaration of Lists_Segments::POST() should be compatible with Lists::POST($name, $reminder, $emailtype, $company, $address_street, $address_street2, $address_city, $address_state, $address_zip, $country, $from_name, $from_email, $subject, $language, $optional_parameters = Array)' at \mailchimp-api-3-0-php\lists\segments\listsSegmentsRoot.php 103:

Backtrace from warning 'Declaration of Lists_Segments::PATCH() should be compatible with Lists::PATCH($patch_params = NULL)' at \mailchimp-api-3-0-php\lists\segments\listsSegmentsRoot.php 103:

Backtrace from warning 'Declaration of Lists_Segment_Segment_Members::POST() should be compatible with Lists_Segments::POST($name, $conditions = NULL, $static_segment = NULL)' at \mailchimp-api-3-0-php\lists\segments\listsSegmentsSegmentMembers.php 54:

**Comment by drewm** [comment]
That code is not from this project.

**Comment by RobertP3469** [comment]
ah... my bad... sorry about that
