### ISSUE TITLE
Unit test coverage

### ISSUE THREAD

**Issue by Insti** [drewm/mailchimp-api#175]
I have a private branch that has 100% test coverage on the `MailChimp` class.

This was achieved by extracting the `curl` specific request handling code into its own class which could be stubbed out to allow canned http responses to be returned so the majority of the tests can run without requiring access to the live Mailchimp servers.

It has fallen a few commits behind the master but if you think this would be a useful addition I can resolve the conflicts and submit a PR.

**Comment by drewm** [comment]
My hesitation is that a big draw of this library for many of its users is the simplicity. You can literally just grab the `Mailchimp.php` file and included it in a page and start using it. We added a second class with the batch operations, but that tends to be a more advanced use-case anyway.

Maintaining that simplicity and portability involves trade-offs in terms of clean architecture, which is always causes me pause for thought. It's a tricky line to walk.

**Comment by drewm** [comment]
One option might be to go down the path of having a stand-alone single file version of the library with all the classes compiled down to a single file.

**Comment by Insti** [comment]
I understand that being able to copy the single `Mailchimp.php` file around is a positive.

I don't think there is any problem with having multiple PHP classes within a single source file. Particularly when they are not intended to be instantiated separately.

When I get a chance I'll submit a PR and we can see how it looks.

**Comment by drewm** [comment]
Closing for now. Feel free to reopen if it becomes relevant again.
