### ISSUE TITLE
Doesn't Work with PHP 7

### ISSUE THREAD

**Issue by rafecolton** [drewm/mailchimp-api#177]
When trying to get lists with PHP 7.0.8, I get the error message `Unknown error, call getLastResponse() to find out what happened.`. When I call `getLastResponse()`, I get a blank response. Same exact code works just fine with 5.6.10:

```
array(3) {
  ["headers"]=>
  array(26) {
    ["url"]=>
    string(57) "https://us2.api.mailchimp.com/3.0/lists?count=10&offset=0"
    ["content_type"]=>
    NULL
    ["http_code"]=>
    int(0)
    ["header_size"]=>
    int(0)
    ["request_size"]=>
    int(0)
    ["filetime"]=>
    int(-1)
    ["ssl_verify_result"]=>
    int(1)
    ["redirect_count"]=>
    int(0)
    ["total_time"]=>
    float(0.441107)
    ["namelookup_time"]=>
    float(0.419261)
    ["connect_time"]=>
    float(0.429059)
    ["pretransfer_time"]=>
    float(0)
    ["size_upload"]=>
    float(0)
    ["size_download"]=>
    float(0)
    ["speed_download"]=>
    float(0)
    ["speed_upload"]=>
    float(0)
    ["download_content_length"]=>
    float(-1)
    ["upload_content_length"]=>
    float(-1)
    ["starttransfer_time"]=>
    float(0)
    ["redirect_time"]=>
    float(0)
    ["redirect_url"]=>
    string(0) ""
    ["primary_ip"]=>
    string(14) "<redacted>"
    ["certinfo"]=>
    array(0) {
    }
    ["primary_port"]=>
    int(443)
    ["local_ip"]=>
    string(10) "<redacted>"
    ["local_port"]=>
    int(54736)
  }
  ["httpHeaders"]=>
  NULL
  ["body"]=>
  NULL
}
``

**Comment by pierre-H** [comment]
Same issue

**Comment by pierre-H** [comment]
With the call : `curl_error($ch)` I discovered this error : 
> SSL certificate : unable to get local issuer certificate

So I did this http://stackoverflow.com/a/31830614 and now it's working

**Comment by robertark** [comment]
When you instantiate the MC object, set the `verify_ssl` property to `false` - see if that works?

Eg:

    $mailchimp = new Mailchimp(MC_API_KEY);
    $mailchimp->verify_ssl = false;

**Comment by terrymun** [comment]
@robertark Do **not** turn off peer verification unless you absolutely know what you're doing/breaking 👎

**Comment by robertark** [comment]
@terrymun I agree, I'm curious to know if it worked though. If so, then I'd question cURL and what changed from php 5.6 to 7.0 -- or if there's just more stringent SSL verifications in newer php versions, but that seems unlikely.

**Comment by tersmitten** [comment]
http://php.net/manual/en/migration56.openssl.php

**Comment by tersmitten** [comment]
http://php.net/manual/de/migration71.incompatible.php#migration71.incompatible.openssl

**Comment by drewm** [comment]
I think this issue is pretty much resolved, so closing for now.

**Comment by robertark** [comment]
@drewm  what's the actual res?

**Comment by drewm** [comment]
@robertark The resolution is get yer darn PHP environment working. Nothing to do with this library.
