### ISSUE TITLE
Additional parameters in signup?

### ISSUE THREAD

**Issue by produktive** [drewm/mailchimp-api#183]
Sorry if this is a novice question but I had been using an old version of this script and users have been notifying me that it has not been working. I updated the file but looking through the examples, how do I now set additional parameters? Does it stay the same? For example, my old file contained this portion:
```
$result = $MailChimp->call('lists/subscribe', array(
            'id' => 'abc123',
            'email' => array(
                'email' => $emailaddress
            ),
            'merge_vars' => array(
                'FNAME' => $firstname
            ),
            'double_optin' => false,
            'update_existing' => true,
            'replace_interests' => false,
            'send_welcome' => false
        ));
```

Can I still use the double_optin => false, send_welcome => false, etc?

**Comment by drewm** [comment]
There's an example of how to do a subscribe in the [README](https://github.com/drewm/mailchimp-api/blob/master/README.md)

The MailChimp docs for a subscribe are here:
http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/
