### ISSUE TITLE
Request returning NULL headers and body

### ISSUE THREAD

**Issue by walshy002000** [drewm/mailchimp-api#185]
Hi all,

Just moved code that was running fine on localhost (albeit by disabling peer check) onto Azure, but when I make the request I just get NULL response, with
`$mc->getLastResponse()`
showing
```
array(2) {
  ["headers"]=>
  NULL
  ["body"]=>
  NULL
}
```

I've followed https://blogs.msdn.microsoft.com/azureossds/2015/06/12/verify-peer-certificate-from-php-curl-for-azure-apps/ to ensure peer verification works. Any suggestions?

**Comment by drewm** [comment]
You might be best asking in a broader Azure context. I think this is most likely nothing to do with the code of this specific library.
