### ISSUE TITLE
How to add product to ecommerce

### ISSUE THREAD

**Issue by marc1986** [drewm/mailchimp-api#187]
Hi. Im trying to add new product from my store based on Symfony using drewm/mailchimp-api
$dataToStore = [
                    'id' => "5",
                    'title' => "5",
                    'handle' => '',
                    'url' => "http://food.fff/tours/5",
                    'description' => 'ddfiosfwncsincaomcsodcm',
                    'type' => '',
                    'vendor' => "getFullName",
                    'image_url' => "http://food.fff/media/cache/tour_item_pic/uploads/images/tour/85/thumbnail_85.jpeg",
                    'variants' => array (
                        'id' => "5",
                        'title' => "title",
                        'url' => "http://food.fff/tours/5",
                        'price' => "5",
                        'image_url' => "http://food.fff/media/cache/tour_item_pic/uploads/images/tour/jpeg",
                        'visibility' => 'visible'
                    )
                ];
                $MailChimp = new MailChimp(<apikey>);
                $res = $MailChimp->post('ecommerce/stores/Foodie/customers', $dataToStore);

But it isn`t work. Can you help me? Thank You

**Comment by drewm** [comment]
I think in your URL `Foodie` should be a store ID. You should refer to the MailChimp API documentation.
