### ISSUE TITLE
Using composer, still getting 2.2

### ISSUE THREAD

**Issue by edalzell** [drewm/mailchimp-api#188]
I have 
```
    "require": {
        "drewm/mailchimp-api": "2.*"
    }
```

in my composer file, but when I open Mailchimp.php, I see v2.2.

I notice on the GH releases page, 2.2 is marked as the latest release, is that the issue?

**Comment by drewm** [comment]
It could be. I'm not entirely sure how that functionality works. Looks like tagging a release is not enough.

**Comment by edalzell** [comment]
Oh, I just noticed that in Mailchimp.php the version is marked as 2.2, that's why I thought I'm getting that version.

I bet I am getting the current version!

Closing this ticket (though maybe update that version number in the source to help w/ the confusion?).
