### ISSUE TITLE
Batch operation limits

### ISSUE THREAD

**Issue by momon** [drewm/mailchimp-api#189]
I'm not entirely sure this is in fact an issue with your wrapper or an API limitation but I couldn't find anything within mailchimp api documentation so I though you would have some hands on experience with this.

Anytime I try to sync up anything above 100 records / operations with the batch script (using PUT), it seems to be failing (it doesn't actually process anything).

If I scale back and send through no more than 100, everything works correctly as expected.

Our actual database has around 20k records or so that we want to keep updated on mailchimp with user information.  I am not expecting to sync up to 20k records on a single call but 100 also feels a bit low.

Would appreciate any sort of input if you've come across any limitation of the sort as described above.

Thanks!

**Comment by drewm** [comment]
Is your connection timing out?

**Comment by momon** [comment]
I am actually not 100% sure.  My setup is a bit complex as I am using your wrapper as an internal API and triggering it from different areas of our network.  I'll try to setup a local test to validate what error it is that I am getting exactly but I doubt it is an actual timeout because it just fails processing within 10 seconds and other requests take longer than that.

I reckon I should have provided the specifics in my first request I was just hoping to find out some info before debugging further.  My apologies, I will update here soon with an actual error if any.

Cheers,

**Comment by momon** [comment]
Ok, I was able to do some further tests and realized this has nothing to do with mailchimp or your wrapper.  It is an environmental issue on my app.  For whatever reason when my post is too large (lets say above 200 records), the post request appears to be getting truncated as it doesn't arrive in full on to the API where I am using your wrapper.  So this is a fault within my own environment that I need to trace down and not strictly related to your wrapper.  My apologies.
