### ISSUE TITLE
Email Content is not updating

### ISSUE THREAD

**Issue by zstergios** [drewm/mailchimp-api#192]
I followed this [artcile](http://thedebuggers.com/send-mailchimp-newsletter-via-php/) instructions.

That example:

`$result = $MailChimp->put('campaigns/' .$compainID. '/content', 
[
      'template' => [
		'id' => '84449', 
        'sections' => ['body_content' => $html]
        ]
]);`

or  putting the HTML directly....

`$template = file_get_contents('template.html');
$result = $MailChimp->put('campaigns/' .$compainID. '/content', 
[
	  'html'=>str_replace('{BODY}',$html,$template),
	  //replace {BODY} tag with HTML dynamic string
]);`

Response for BOTH is

`Array
(
    [type] => http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/
    [title] => Bad Request
    [status] => 400
    [detail] => Your Campaign is not ready to send.
    [instance] => 
)`

http://prntscr.com/fc0pvw

Any clue???

**Comment by drewm** [comment]
Is there something specific that's leading you to think this issue originates with this library?

**Comment by terrymun** [comment]
That is probably because you are sending your campaign from an email with a domain that is yet to be verified: http://kb.mailchimp.com/accounts/email-authentication/verify-a-domain

**Comment by Norelles** [comment]
I had the same problem. ID of template has to be an integer, not a string ;)

**Comment by gt7810** [comment]
@Norelles Yes taking out the quotes around template id fixed this for me. Thanks!
