### ISSUE TITLE
Invalid Email Address with +aliases

### ISSUE THREAD

**Issue by robinwkurtz** [drewm/mailchimp-api#193]
Hello! Great wrapper, thanks for the share.

I am running into an issue and I am not sure if it's on the Wrapper's end or Mailchimps. I am unable to add email addresses with aliases, i.e. robinwkurtz+test@gmail.com. The reason this is an issue, is for dev work, and testing out opt in paths without having to remove our emails each time.

Code:
```
$this->load->library('MailChimp');
$list_id = $this->config->item('Mailchimp_list_automation');
$result = $this->mailchimp->post("lists/$list_id/members", [
	'email_address' => $_GET['e'],
	'status' => 'subscribed', // subscribed
	'source => 'Welcome Email - Optin',
]);
$data['result'] = $result;
```

Result:
```
array(5) { ["type"]=> string(77) "http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/" ["title"]=> string(16) "Invalid Resource" ["status"]=> int(400) ["detail"]=> string(37) "Please provide a valid email address." ["instance"]=> string(0) "" }
```

Thanks!

**Comment by pdbreen** [comment]
The code above may be a snippet for the sample, but I'd double check you don't need an urldecode to unpack your url parameters.  Also, I'd NEVER pass data directly pulled from $_GET anywhere!  So, possibly something like this:

```
$email = urldecode($_GET['e'] ?? '');
if (!filter_var($email, FILTER_VALIDATE_EMAIL) !== false) {
// add to list
}
```

**Comment by robinwkurtz** [comment]
Thanks @pdbreen, massive oversight! The email was being sent to the wrapper with the space.
