### ISSUE TITLE
 Undefined offset in curl headers

### ISSUE THREAD

**Issue by romanopablo** [drewm/mailchimp-api#197]
Hi, 
im using this library in a server with a proxy config, and im getting a "Undefined offset" at MailChimp.php line 305 because the response has  2 headers with http code (one from the proxy and another from the mailchimp server):

**HTTP/1.1 200 Connection established**\r\n
\r\n
**HTTP/1.0 200 OK**\r\n
Server: openresty\r\n
Content-Type: application/json; charset=utf-8\r\n
Content-Length: 306\r\n
X-Request-Id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx\r\n
Link: <https://usxx.api.mailchimp.com/schema/3.0/Batches/Instance.json>; rel="describedBy"\r\n
Content-Encoding: gzip\r\n
Vary: Accept-Encoding\r\n
Date: Mon, 19 Jun 2017 11:44:55 GMT\r\n
Connection: close\r\n
Set-Cookie: _AVESTA_ENVIRONMENT=prod; path=/\r\n
\r\n

I've solved this in my proyect striping the 2 first lines in the headers with:

`$headersAsString = preg_replace("/^(.*\n){2}/", "", $headersAsString);`

Maybe someone can experience the same issue.

**Comment by drewm** [comment]
If I'm reading the spec properly, I don't *think* that's a valid response from your proxy.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

But it's the response you've got, so that looks like a reasonable way of dealing with it.

**Comment by romanopablo** [comment]
I assumed that was a proxy response, but needed to revolve it fast so that was my fix. You can close the issue, i just wanna leave this in the case that some experience the same problem. Thanks for this awesome wrapper, saves a lot of time!
