### ISSUE TITLE
Batch process 100% error rate

### ISSUE THREAD

**Issue by LiamMcArthur** [drewm/mailchimp-api#198]
I'm trying to create a batch process within a foreach statement but I'm getting 100% of my transactions fail:

**Array ( [batches] => Array ( [0] => Array ( [id] => 003b4e8459 [status] => finished [total_operations] => 110 [finished_operations] => 110 [errored_operations] => 110 [submitted_at] => 2017-06-21T09:37:42+00:00 [completed_at] => 2017-06-21T09:37:50+00:00 [response_body_url]**

 My code is as follows. Is there something obvious that I'm doing wrong here? The .gz error log file says The requested method and resource are not compatible. I've tried it with `patch` but this doesn't seem to work either:

```
foreach($orders as $order) {

            $data = new WC_Order($order->ID);
            $meta = get_post_meta($order->ID);
            $email_address = $data->get_billing_email();
            $subscriber_hash = md5(strtolower($email_address));

            // Cover Start Date Conversion
            $cover_start_date = $meta['coverstart'][0];
            $cover_start_date = DateTime::createFromFormat('d/m/Y', $cover_start_date);
            $cover_start = $cover_start_date->format('Y/m/d');

            // Cover End Date Conversion
            $cover_end_date = DateTime::createFromFormat('d/m/Y', $meta['coverstart'][0]);
            $cover_end_date->modify('-1 day');
            $cover_end_date->modify('+1 year');
            $cover_end = $cover_end_date->format('Y/m/d');

            $Batch->put("op" . $i, "lists/$list_id/members", [
                'email_address' => $email_address,
                'status'        => 'subscribed',
                'merge_fields' => [
                    'FNAME' => $data->get_billing_first_name(),
                    'LNAME' => $data->get_billing_last_name(),
                    'COVERSTART' => $cover_start,
                    'COVEREND' => $cover_end,
                ]
            ]);

            $i++;

}

$result = $Batch->execute();
$status = $Batch->check_status();
print_r($status);
```

**Comment by drewm** [comment]
Have you tried the basic batch example from the docs?

**Comment by LiamMcArthur** [comment]
I've resorted in using the ordinary `$Mailchimp->put` within my foreach statement as I've still been having problems getting batch working - although this seems to take much longer to finish running.

**Comment by nrishoj** [comment]
Yeah, I get the same error.

> The requested method and resource are not compatible. See the Allow header for this resource's available methods.

Hope you'll have the time to look over this soon'ish. Sending requests per single subscriber can be time consuming ;-)

Thanks for an awesome package @drewm.

**Comment by LiamMcArthur** [comment]
@nrishoj I'm glad it's not just me!

**Comment by drewm** [comment]
Has anyone verified that this is an issue with this library rather than the payload sent or something at MailChimp's end?

**Comment by jasperjorna** [comment]
Looks like it mandatory to provide the MD5 hash of the e-mail address when using a PUT request.

This worked for me:

```php
$batch = $mailchimp->new_batch();

foreach ($subs as $key => $sub) {
    $batch->put('op'.$key, 'lists/'. $id . '/members/' . md5('f3ada405ce890b6f8204094deb12d8a8'), [
        'email_address' => 'foo@bar.com',
        'status_if_new' => 'subscribed',
        'merge_fields'  => [
            'FNAME' => 'Foo',
            'LNAME' => 'Bar',
        ]
    ]);
}

$result = $batch->execute();
```

**Comment by LiamMcArthur** [comment]
Ahh! Much appreciated @jasperjorna. This means I can put my PHP timeout back to normal now!
