### ISSUE TITLE
SSL certificate: unable to get local issuer certificate

### ISSUE THREAD

**Issue by x1a0** [drewm/mailchimp-api#2]
When I deploy the codes to server PHP cURL got this error:

```
SSL certificate: unable to get local issuer certificate
```

Maybe it's better to add `CURLOPT_SSL_VERIFYPEER => 0`?

**Comment by drzraf** [comment]
Still waiting for mailchimp to change their certificate, but would be still safer to use:
```file_get_contents("https://us1.api.mailchimp.com/export/1.0/list", false, stream_context_create(["ssl" => ["peer_fingerprint" => ["sha1" => "46715798A08AD8C06FAB1D5EECA7C340B52BDCC3"], "verify_peer" => FALSE]]));```

At least their certificate's fingerprint is checked which, unless I'm mistaken, by far better than nothing.

Fingerprint obtained from openssl s_client + openssl x509  -fingerprint
