### ISSUE TITLE
the requested package drewn/mailchimp-api could not be found in any version

### ISSUE THREAD

**Issue by festlanky** [drewm/mailchimp-api#20]
i tried to install drewn/mailchimp-api with this strings
{
    "require": {
        "drewm/mailchimp-api": "*"
    }  
}
 and i get this error;   Problem 1
    - The requested package drewm/mailchimp-api could not be found in any versio
n, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common
 problems.

**Comment by sineld** [comment]
Thanks @JamesLaugesen this solved my issue.
