### ISSUE TITLE
basic example not working

### ISSUE THREAD

**Issue by tdias25** [drewm/mailchimp-api#201]
i just downloaded it and copied the example code, but it doesnt work, here's my code:

```
require_once('lib/mailchimp_2/src/MailChimp.php');
use \DrewM\MailChimp\MailChimp;


	define('MAILCHIMP_API_KEY',  'xxxxxxxxxxxxxxxxxxxxxx-us16');
	define('MAILCHIMP_LIST_ID',  'xxxxxxxxxxxx'); 
	define('MAILCHIMP_NAME_TAG', 'SAMPLE'); 

	$MailChimp = new MailChimp(MAILCHIMP_API_KEY);
	$result = $MailChimp->get('lists');
	var_dump($result);

```
it returns false;

my  API key ends with "-us16" and the example with "-us1", does it matter?

**Comment by romanopablo** [comment]
Can you make a `echo  $MailChimp->getLastError();` for debugging?

**Comment by afreakk** [comment]
Hi, seems you have prefix '3.0/' on all the methods to make it work.
Like this:
            $result = $MailChimp->get('3.0/lists');
and this:
            $result = $MailChimp->post("3.0/lists/$listId/members", [

then it seems to work fine.

**Comment by AlonEitan** [comment]
If you're running from localhost / non-https then you need to set the following:

    $MailChimp = new MailChimp( 'XXXXXXX' );
    $MailChimp->verify_ssl = false;

**Comment by panadol007** [comment]
Same problem here I have; it has strange behaviour where i tried 'curl -v xxx'. It throws me error 401, until i restart my terminal. 

However, it still give me 

> Your API key may be invalid, or you've attempted to access the wrong datacenter

Any clue would be so much appreciated.
