### ISSUE TITLE
WordPress with WooCommerce

### ISSUE THREAD

**Issue by danielmoorehbd** [drewm/mailchimp-api#206]
Hi there,
How would one go about installing this to a WordPress site running WooCommerce?

**Comment by drewm** [comment]
This isn't a complete solution. It's just a library for making it simpler to write code against the MailChimp API.

**Comment by danielmoorehbd** [comment]
Ah... Chances are I only need a snippet anyways, I am trying to follow this:
[Link](https://stackoverflow.com/questions/45711724/woocommerce-check-mailchimp-subscribers-before-allowing-coupon?noredirect=1#comment78390746_45711724)

**Comment by danielmoorehbd** [comment]
helpful...

**Comment by drewm** [comment]
Eh? You'd said you'd found something to follow, so it sounded like you were done.

But anyway, if you have a problem with the way this library works feel free to raise an issue. Otherwise you might be better sticking to StackOverflow with your implementation design questions.
