### ISSUE TITLE
Getting values from all the lists

### ISSUE THREAD

**Issue by kevinkt** [drewm/mailchimp-api#207]
How would I access the values of the array returned from 

`$lists = $MailChimp->get('lists');`

I'm currently using

```
$x = 0;

foreach($lists as $list){
	
	$listId = $list['lists'][$x]['id'];
	$listName = $list['lists'][$x]['name'];

$x++;
}
```

However, this isn't working.

**Comment by drewm** [comment]
Hi, please take questions about _your code_ to a general place like StackOverflow, so we can keep the issues here about this library.
