### ISSUE TITLE
Why Composer? 

### ISSUE THREAD

**Issue by amityweb** [drewm/mailchimp-api#21]
Why is the install process stating to use Composer? Composer installs tonnes of other unnecessary files, and all to avoid this line:

include('MailChimp.php');

You also state use it to install dependencies. What dependencies are there for this file, I cant see any. 

It looks to me as if we can just upload the file and use this include line, then we can instantiate a new MailChimp class right away. 

Composer is over the top for this - unless your app uses composer, then fine, but you should include "normal" instructions. Many users don't use composer, so you are just overcomplicating a simple task. 

My two cents!

**Comment by RVN-BR** [comment]
If a "developer" had trouble looking at this repo and doing a simple include...erm.. change developers?

Adding the composer instructions is pretty much de facto now adays.... I dont use composer for everything, but occasionally its useful...

But I navigate around when needed...

Anyways, dont want to bring this from the dead, just one suggestion, if possible bump the package version to something other than dev-master, it makes it easier to stick to a version for produciton, etc... thanks!!
