### ISSUE TITLE
This campaign cannot be scheduled

### ISSUE THREAD

**Issue by Gmulti** [drewm/mailchimp-api#211]
Hi,

I want use POST : `/campaigns/$campaignId/actions/schedule`

I use a test parameter:

```php
$params =  array(
        'schedule_time' => "2017-12-04T19:13:00+00:00",
       "timewarp" => false,
       "batch_delay" => false
);
```

And i have this response : `This campaign cannot be scheduled`

Has anyone ever had this error on behalf of Mailchimp ?
Thanks

**Comment by xteron** [comment]
Hi!

Check Mailchimps documentation for the "schedule_time" parameter: 

> The date and time in UTC to schedule the campaign for delivery. Campaigns may only be scheduled to send on the quarter-hour (:00, :15, :30, :45).

ref: http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/#action-post_campaigns_campaign_id_actions_schedule

**Comment by Gmulti** [comment]
Hi,

Even with this setting, it does not work : 
`2017-12-04T19:13:00+00:00`

**Comment by xteron** [comment]
Have you tried this? 

> 2017-12-04T19:00:00+00:00

**Comment by Gmulti** [comment]
Yes but it still does not work...
I regenerated an API key and it works again ... strange!

**Comment by drewm** [comment]
Sounds like you have it working, so closing for now.

**Comment by Navani-cpu** [comment]
{
    "type": "https://mailchimp.com/developer/marketing/docs/errors/",
    "title": "Bad Request",
    "status": 400,
    "detail": "This campaign cannot be scheduled: .",
    "instance": "8de90dbf-5930-9156-7164-8adcc3b997bc"
}
