### ISSUE TITLE
Issue started to happen in development

### ISSUE THREAD

**Issue by Pixney-William** [drewm/mailchimp-api#215]
I just discovered that the functionality has changed recently and i wonder if there has been any changes added recently? I have always been able to use locally. But it is not working now. Not even if i set `$MailChimp->verify_ssl = false`.

This is not happening in production with the exact same codebase, with the difference of it having an SSL Cert.

`$MailChimp->getLastError()` tells me `Unknown error, call getLastResponse() to find out what happened.`

And this is the response of `$MailChimp->getLastResponse()` : 

I just noticed that when i tested this in development (without SSL) it has stoped working suddenly. In production and with the same code it works (has ssl).

Even if i do `$MailChimp->verify_ssl = false` it doesn't work. 

`$MailChimp->getLastResponse()` is null for both httpHeaders  and body. Any recent changed? 

Headers is:

```
array:3 [▼
  "headers" => array:26 [▼
    "url" => "https://us8.api.mailchimp.com/3.0/lists/xxxxxxxx/members"
    "content_type" => null
    "http_code" => 0
    "header_size" => 0
    "request_size" => 0
    "filetime" => -1
    "ssl_verify_result" => 0
    "redirect_count" => 0
    "total_time" => 0.072644
    "namelookup_time" => 0.029605
    "connect_time" => 0.052057
    "pretransfer_time" => 0.0
    "size_upload" => 0.0
    "size_download" => 0.0
    "speed_download" => 0.0
    "speed_upload" => 0.0
    "download_content_length" => -1.0
    "upload_content_length" => -1.0
    "starttransfer_time" => 0.0
    "redirect_time" => 0.0
    "redirect_url" => ""
    "primary_ip" => "xxx.xxx.xxx.xxx"
    "certinfo" => []
    "primary_port" => 443
    "local_ip" => "xxx.xxx.xxx.xxx"
    "local_port" => 56483
  ]
  "httpHeaders" => null
  "body" => null
]
```

**Comment by Pixney-William** [comment]
`$this->last_error` on line 252 in MailChimp.php shows `SSL certificate problem: Couldn't understand the server certificate format` if i dump it.

**Comment by Pixney-William** [comment]
Starting to think this has to do with my macs built in version of SSL.

**Comment by drewm** [comment]
I think this is specific to your environment. If you have more information that indicates that it's a problem with the library, feel free to post back.
