### ISSUE TITLE
get request pagination

### ISSUE THREAD

**Issue by imperialjeff** [drewm/mailchimp-api#221]
I can see nowhere in the readme, nor anywhere in the code, to add query parameters. I'm after the pagination (count, offset) arguments in particular. Is there a way of setting these?

`$results= $MailChimp->get("lists/$list_id/members/");`

**Comment by pdbreen** [comment]
`$results= $MailChimp->get("lists/{$list_id}/members?count=100");`

**Comment by terrymun** [comment]
See the official API docs: https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#read-get_lists_list_id_members

You simply need to add these parameters in the query string after the URL.

**Comment by imperialjeff** [comment]
@pdbreen That hasn't worked for me. What did work was the following:
```
case 'get':
                $query = http_build_query($args, '', '&');
                **$query = $query . '&count=9999';**
                curl_setopt($ch, CURLOPT_URL, $url . '?' . $query);
                break;
```
Line 200 of MailChimp.php

**Comment by drewm** [comment]
I think this should work:

```php
$results= $MailChimp->get("lists/{$list_id}/members", [
    'count' => 100,
 ]);
```

Count is just another argument to the method.

**Comment by imperialjeff** [comment]
@drewm Sadly, that's the first thing I tried as it made the most sense. No joy.

What did work was appending the count query string to the `get` case, see above.

**Comment by pdbreen** [comment]
@imperialjeff - your hack url result should be no different than the example by @drewm where 'count' parameter is passed via the args array. Has to be something else coming into play - both the direct query append I shared and the preferred example from Drew are working fine for me.
