### ISSUE TITLE
Interests: schema describes boolean, string found instead

### ISSUE THREAD

**Issue by jonathanstegall** [drewm/mailchimp-api#222]
I'm trying to add a subscriber to a list with interest groups. I'm currently using the CocoaRestClient to send the POST call to this library, which then sends to MailChimp via `/lists/[listid]/members`. My request params are like this:

email_address: test@whatever.com
status: subscribed
merge_fields[FNAME]: first
merge_fields[LNAME]: last

This works. A subscriber is successfully added.

But when I try to add interests, the request fails. Here's an example array:

```
Array(
	[email_address] => test@whatever.com
	[status] => subscribed
	[merge_fields] => Array(
		[FNAME] => first
		[LNAME] => last
	)
	[interests] => Array(
		[myinterestid] => true
	)
)
```

Here is the error result:

```
"errors": [
    {
      "field": "interests.myinterestid",
      "message": "Schema describes boolean, string found instead"
    }
  ]
```

I've tried using this code before sending my `$params` to the wrapper, as it helped with the `merge_fields`, but it does not seem to affect the interests:

```
foreach ( $params as $key => $value ) {
	if ( is_array( $value ) ) {
		foreach ( $value as $subkey => $subvalue ) {
			if ( 'true' === $subvalue ) {
				$subvalue = true; // try to force a boolean in case it is a string
			}
			$value[ $subkey ] = sanitize_text_field( $subvalue );
		}
	} else {
		$params[ $key ] = sanitize_text_field( $value );
	}
}
```

**Comment by jonathanstegall** [comment]
I'm realizing this happens because `json_encode` seems to convert everything to a string, unless for example `JSON_NUMERIC_CHECK` is applied. MailChimp then complains about the integer, though.

Are there any examples of successfully passing interests with this wrapper?

**Comment by pdbreen** [comment]
When I do a print_r of the args just before the call, my PHP true becomes a 1 in the print_r output (below, along with json_encoded version that shows true boolean value).  Since your's still shows true, it definitely seems like you're passing a string, not a boolean.  

Can you share the code where you construct the args?  The problem has got to be there - may need a filter_var($var, FILTER_VALIDATE_BOOLEAN) if the value is coming externally.

print_r of args
```
Array
(
    [email_address] => xxxx+1512670398@gmail.com
    [status] => subscribed
    [email_type] => html
    [merge_fields] => Array
        (
            [DISC50] => DISC5031654
            [DISC50_EXP] => 2018-01-20
            [SOURCE] => discount50
            [ADD_DATE] => 2017-12-07
        )

    [interests] => Array
        (
            [1b457f4efe] => 1
        )

)
```

json_encode of same
```
{"email_address":"xxxx+1512670398@gmail.com","status":"subscribed","email_type":"html","merge_fields":{"DISC50":"DISC5031654","DISC50_EXP":"2018-01-20","SOURCE":"discount50","ADD_DATE":"2017-12-07"},"interests":{"1b457f4efe":true}}
```

**Comment by pdbreen** [comment]
@jonathanstegall just re-read your original post.  If you're not using mailchimp-api wrapper, why are you posting question here?  Shouldn't you be posting to mmattozzi/cocoa-rest-client repo?

**Comment by jonathanstegall** [comment]
@pdbreen No, I'm only using the cocoa api client to create requests to send to this wrapper. I don't have my forms built yet so I'm using the cocoa client as a test client, and the wrapper as the server. Then I have a method where I'm passing those parameters to this wrapper.

As I mentioned above, before I send my parameters to mailchimp-api wrapper, I run this when the app receives the parameters:

```
foreach ( $params as $key => $value ) {
	if ( is_array( $value ) ) {
		foreach ( $value as $subkey => $subvalue ) {
			if ( 'true' === $subvalue ) {
				$subvalue = true; // try to force a boolean in case it is a string
			}
			$value[ $subkey ] = sanitize_text_field( $subvalue );
		}
	} else {
		$params[ $key ] = sanitize_text_field( $value );
	}
}

// then pass it to this wrapper ($call is the list/id/members param)
$result = $this->mailchimp_api->post( $call, $params );
```

So I check to see if the value is 'true', there, and if it is I force it to be true instead. I pass `$params` to the wrapper here, which I'm calling `mailchimp_api`. This works, at least according to my logging.  And it successfully creates the list member if there isn't the boolean issue. Once it gets passed to json_encode, true becomes a string again.

I had tried using a filter_var as you mentioned but this has been unsuccessful.

Before the Mailchimp class (in this wrapper) runs `json_encode` I get this, when I log the params:

```
Array(
	[email_address] => test@whatever.com
	[status] => subscribed
	[merge_fields] => stdClass Object(
		[FNAME] => first
		[LNAME] => last
	)
	[interests] => stdClass Object(
		[04471b1571] => 1
	)
)
```

Right after `json_encode` runs, I get this:

```
{"email_address":"test@whatever.com","status":"subscribed","merge_fields":{"FNAME":"first","LNAME":"last"},"interests":{"04471b1571":"1"}}
```

**Comment by pdbreen** [comment]
Try this change to your filter - essentially, don't run the converted boolean through sanitize_text_field which I'm guessing is turning it back into a string.

```
			if ( 'true' === $subvalue ) {
				$value[ $subkey ] = true; // try to force a boolean in case it is a string
			} else if ('false' === $subvalue) {
				$value[ $subkey ] = false; // try to force a boolean in case it is a string
			} else {
				$value[ $subkey ] = sanitize_text_field( $subvalue );
			}
```

**Comment by jonathanstegall** [comment]
@pdbreen This appears to work. It does seem weird that it was outputting it as a boolean after the `sanitize_text_field`, once it arrived in MailChimp.php, but even so this works; I'll take it. Thanks much.

**Comment by pdbreen** [comment]
With print_r output, you really can't tell if its a string or boolean or number since it doesn't quote strings.  If you have access to dump(), its a bit easier to see what's what.  If not, dump the output of json_encode (as you have) but trust that if it shows quotes, it was given a string as input and not a value.

**Comment by emmitt22991** [comment]
to send integers (i.e. campaign id's):  

Edit this function in MailChimp.php:

private function attachRequestPayload(&$ch, $data)
    {
        $encoded                    = json_encode($data, JSON_NUMERIC_CHECK);
        $this->last_request['body'] = $encoded;
        curl_setopt($ch, CURLOPT_POSTFIELDS, $encoded);
    }

**** added this to json_encode...

 , JSON_NUMERIC_CHECK
