### ISSUE TITLE
Too many recent signup requests

### ISSUE THREAD

**Issue by danyj** [drewm/mailchimp-api#226]
I know that this is not the API related but you might be able to shed some light . 

Few emails that have signed up via API get the 

`Recipient "" has too many recent signup requests`  error , 

I also get this when I try to add the email in Mailchimp directly

![tkfr5r6zqcuszbda5iq02g](https://user-images.githubusercontent.com/2340172/35332803-9ae450f2-010c-11e8-8b6e-38705363ea21.png)

should I take the Mailchimp word for it or ? 

the API I am using is 

```
$list_id = 'b1234346';

$result = $MailChimp->post("lists/$list_id/members", [
				'email_address' => 'davy@example.com',
				'status'        => 'subscribed',
			]);
```

**Comment by drewm** [comment]
If you get the same response from the API as the MailChimp user interface, then yes, take the API's word for it. Either way, MailChimp support will be able to help you better than me.
