### ISSUE TITLE
Request more than ten lists

### ISSUE THREAD

**Issue by BenAttenborough** [drewm/mailchimp-api#227]
Hi, on my project we have more than ten lists, but

```
$MailChimp->get('lists');
```

only returns 10 lists. I believe this is the expected behaviour, but I wondered if it is possible to pass an argument to get('lists') to get more than ten. I tried something like:

```
$result = $MailChimp->get( 'lists', [
	'count' => 100
]);
```

And that seems to work. But it would be better to fetch the number of lists and use this instead of an arbitrary large number. So I did this:

```
$lists = $MailChimp->get( 'lists');
$maxLists = $lists['total_items'];
$result = $MailChimp->get( 'lists', [
	'count' => $maxLists
]);
```

Seems a bit redundant to fetch the lists twice, once to get the number and then to get all the lists, but it seems to work. I wonder if this could be explained a bit in the readme? I took me a while to figure out!

**Comment by drewm** [comment]
Hi! 
I see what you're saying, but I think MailChimp has designed it that way or encourage you _not_ to try to retrieve everything at once.

However, this is actually a discussion of the design of MailChimp's API and nothing really to do with this PHP library, so closing for now. You could offer this feedback to MailChimp.
