### ISSUE TITLE
Delete function not working...

### ISSUE THREAD

**Issue by agamemnus** [drewm/mailchimp-api#228]
````
$subscriber_hash = $MailChimp->subscriberHash($email_address);
 $MailChimp->delete("lists/$mailchimp_list_id/members/$subscriber_hash");
````

"Fatal error: Call to a member function subscriberHash() on a non-object in ..."

**Comment by drewm** [comment]
`$MailChimp` should be an instance of the `MailChimp` class. Please refer to the first example in the Readme.

**Comment by agamemnus** [comment]
Oh, thank you. I didn't notice. Not enough sleep.
