### ISSUE TITLE
It is not so good to share api_key in "Invalid MailChimp API key `{$api_key}` supplied." message

### ISSUE THREAD

**Issue by ildar-aim** [drewm/mailchimp-api#229]
https://github.com/drewm/mailchimp-api/blob/059792f1f1a467834397ead38f245bdfcd09fc4a/src/MailChimp.php#L49

It may be a private information of merchants.

**Comment by drewm** [comment]
I think this will most likely happen for developers during development, as they get things correctly configured. But yes, you're right. Perhaps we should rethink how that works.

**Comment by Pixney-William** [comment]
The extra  information (the key) is not needed. Simple statement that the key is invalid is enough. As a developer you know what to look for from that message.

**Comment by drewm** [comment]
Ok, great. So is either of you going to make the change?

**Comment by Pixney-William** [comment]
https://github.com/drewm/mailchimp-api/pull/231

**Comment by drewm** [comment]
Thanks both.
