### ISSUE TITLE
not able to get member count

### ISSUE THREAD

**Issue by mware** [drewm/mailchimp-api#244]
Thanks for the helpful wrapper. 

I'm trying to pull the member count from a particular list but an getting nothing in return.

```
$list_id = '5ec0d6d938';
$result = $MailChimp->get('lists/$list_id/stats/member_count');
print_r($result);
```

This returns 
`
Array ( [type] => http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ [title] => Resource Not Found [status] => 404 [detail] => The requested resource could not be found. [instance] => 63bac9d5-5b63-4b12-b472-f7cc6c1ebc60 )
`

Am I doing something incorrectly? Thx.

**Comment by pdbreen** [comment]
PHP won't substitute variables in single quoted strings.  Change parameter to get() to use double quotes.

**Comment by jeckyl** [comment]
Hi,

Read the MailChimp guide to get right datas http://developer.mailchimp.com/documentation/mailchimp/reference/lists/#read-get_lists_list_id

**Comment by mware** [comment]
I'll read more. thanks.
