### ISSUE TITLE
Europe GDPR regulation 

### ISSUE THREAD

**Issue by oitsuki** [drewm/mailchimp-api#248]
Must be include or not ?

**Comment by maxhelias** [comment]
It's just an SDK to communicate with the MailChimp API, there is nothing to take care of

**Comment by Zauberfisch** [comment]
I agree, it's not in the project scope to have special handling for GDPR. Though some documentation is needed for how to set the marketing permissions.
I've made a start in #271, bot some extra documentation would surely be a good.
