### ISSUE TITLE
Timeout variable not precise enough?

### ISSUE THREAD

**Issue by ArondeParon** [drewm/mailchimp-api#250]
Over the past 2 months I have had 7 "Unknown errors" that actually seem to be timeouts.

When inspecting my response headers, each of these cases have a "total" time value of `9.99...`. 

![image](https://user-images.githubusercontent.com/7697/45148310-4809a500-b1c7-11e8-9efa-64ad1cf83a02.png)

Is there a way to resolve this?

**Comment by drewm** [comment]
I'm not quite sure what you're asking here.

**Comment by ArondeParon** [comment]
You can ignore this issue. Looking at my question now, I am not sure where my head was at at that time 😏 

This is a cURL issue.
