### ISSUE TITLE
Why is HTTP 1.0 forced?

### ISSUE THREAD

**Issue by cyphix333** [drewm/mailchimp-api#251]
Just looking at the cURL code and seen this:

`curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_0);`

Shouldn't we either be leaving this as the default or forcing 1.1? Is there a reason 1.0 is forced?

**Comment by drewm** [comment]
Fair point, I'm not sure why. I'll remove it and we can see if anything breaks.
