### ISSUE TITLE
New tags feature

### ISSUE THREAD

**Issue by prema770** [drewm/mailchimp-api#254]
Thanks very much for the API - it's working very well for us. Is there any intention to add the new tags feature - replacing segments? 
Does anyone know ho to do this

**Comment by drewm** [comment]
Can you post the URL of the part of the MailChimp API you're talking about?

**Comment by emmitt22991** [comment]
https://mailchimp.com/help/getting-started-tags/?_ga=2.210687701.1130180203.1541173921-1712706834.1531779109

https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/tags/

**Comment by drewm** [comment]
I don't see what specific support you'd need in order to use that part of the API. What am I missing?

**Comment by emmitt22991** [comment]
I just saw you ask for the part of the API so I answered.  Looking at your docs, would this be the syntax to include tags?

$list_id = 'b1234346';
$subscriber_hash = $MailChimp->subscriberHash('davy@example.com');

$result = $MailChimp->patch("lists/$list_id/members/$subscriber_hash", [
				'merge_fields' => ['FNAME'=>'Davy', 'LNAME'=>'Jones'],
				'tags'    => ['name' => 'Houston', 'status' => 'active'],
			]);

print_r($result);

**Comment by emmitt22991** [comment]
Actually, that syntax did not work.... I'm having trouble applying the tags... has anyone else figured out the correct syntax?

**Comment by emmitt22991** [comment]
OK, figured it out...

$list_id = 'b1234346';
$subscriber_hash = $MailChimp->subscriberHash('davy@example.com');

$result = $MailChimp->post("lists/$list_id/members/$subscriber_hash/tags", [
'tags' => [
     [
          'name' => 'Houston', 
          'status' => 'active'
     ],
     [
          'name' => 'New Customer',
          'status' => 'active'
]
]);

print_r($result);

**Comment by emmitt22991** [comment]
Will return 1 if successful, an array of information if an error

**Comment by mattmintun** [comment]
@emmitt22991 - this worked for me as well!

**Comment by drewm** [comment]
Great, looks like it's working so I'll close this.

**Comment by BB-000** [comment]
In case any one else finds this, this also works (because 'tags' & 'segments' have the same API endpoint)
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/segments/members/

```
$addToSegment = $MailChimp->post("lists/{{LISTID}}/segments/{{SEGMENTID}}/members/", [
    "email_address" => "{{EMAIL}}"
]);
```

**Comment by BB-000** [comment]
I stumbled across this again, ended up using emmitt22991's solution as it seemed impossible to find the 'SEGMENTID' of a static segment (tag)
