### ISSUE TITLE
Improve Travis

### ISSUE THREAD

**Issue by maxhelias** [drewm/mailchimp-api#258]
Hello,

I would like to improve the Travis integration.

In first, I like to delete the travis.sh file to run the tests on all the PHP envrionments and not only the 7.1 version, copy the .env and fill some variables that should fix the Travis errors

WDYT ?

**Comment by drewm** [comment]
Did you manage to come up with anything?

**Comment by maxhelias** [comment]
No, I do not really have time to look it now.
Maybe later if nobody wants to try
