### ISSUE TITLE
Error when subscribing member with marketing permissions (Schema describes array, object found instead))

### ISSUE THREAD

**Issue by RicLeP** [drewm/mailchimp-api#264]
When trying to set a member’s marketing permissions I get the following error: Schema describes array, object found instead

I am passing an array to the marketing permission, but guess it’s being converted to an object like how ‘interests’ are?

`
$payload = [
	'email_address' => Input::get('email'),
	'status' => 'subscribed',
	'merge_fields' => Input::get('merge_fields'),
	'interests' => $interests,
	'marketing_permissions' => [
		'marketing_permission_id' => $emailMarketingPermissionId,
		'enabled' => true
	]
];
`

Error:
["field"]=>
      string(21) "marketing_permissions"
      ["message"]=>
      string(44) "Schema describes array, object found instead"

**Comment by pdbreen** [comment]
You're passing an object.  Try this - note the extra `[ ]` to change from passing an object to passing an array of objects.

```
$payload = [
    'email_address' => Input::get('email'),
    'status' => 'subscribed', 
    'merge_fields' => Input::get('merge_fields'), 
    'interests' => $interests, 
    'marketing_permissions' => [ 
        [ 'marketing_permission_id' => $emailMarketingPermissionId, 'enabled' => true ] 
    ]
];
```

**Comment by RicLeP** [comment]
Thank you.
