### ISSUE TITLE
Batch operations has error

### ISSUE THREAD

**Issue by ducnguyenhuy** [drewm/mailchimp-api#265]
Followed this https://github.com/drewm/mailchimp-api#batch-operations
Got error: "title":"API Key Missing","status":401,"detail":"Your request did not include an API key."

But try to call get lists from MailChimp works well.

Thanks.

**Comment by ducnguyenhuy** [comment]
@drewm Could you please suggest solution to fix?

**Comment by drewm** [comment]
What steps have you taken to debug it?

**Comment by ducnguyenhuy** [comment]
After run batch and i have used 

> $MailChimp->new_batch($batch_id);
$result = $Batch->check_status();

and saw Error above

**Comment by ducnguyenhuy** [comment]
I'm talking missing api keys but get lists works. Weird.

**Comment by ducnguyenhuy** [comment]
@drewm Please let me know if you need more info

**Comment by ducnguyenhuy** [comment]
@drewm Finally, I found that I had a wrong List ID. I wish it can give me a correct error message. 

Let me close this. Thanks.
