### ISSUE TITLE
ErrorException: Undefined offset: 1 in  drewm/mailchimp-api/src/MailChimp.php:340

### ISSUE THREAD

**Issue by sebestenyb** [drewm/mailchimp-api#267]
I think there's some problem how the HTTP1.1 responses are handled.
There's an assumption at line https://github.com/drewm/mailchimp-api/blob/master/src/MailChimp.php#L331 that only the first line in the response is the http status, but with HTTP1.1 it's not true:
```
[2019-03-25 11:19:16] production.DEBUG: HTTP/1.1 100 Continue
[2019-03-25 11:19:16] production.DEBUG:
[2019-03-25 11:19:16] production.DEBUG: HTTP/1.1 200 OK
```

It causes an error at https://github.com/drewm/mailchimp-api/blob/master/src/MailChimp.php#L340, as there's no `:` in the line.

Here's the full output of the MailChimp API:

```
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Server: openresty
Content-Type: application/json; charset=utf-8
Content-Length: 4240
X-Request-Id: ...
Link: <https://us14.api.mailchimp.com/schema/3.0/Campaigns/Content/Collection.json>; rel="describedBy"
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Encoding: gzip
Vary: Accept-Encoding
Date: Sun, 24 Mar 2019 22:37:01 GMT
Connection: keep-alive
Set-Cookie: _AVESTA_ENVIRONMENT=prod; path=/
Set-Cookie: _mcid=...; expires=Mon, 23-Mar-2020 22:37:00 GMT; Max-Age=31536000; path=/; domain=.mailchimp.com
Set-Cookie: PHPSESSID=...; path=/
```

**Comment by ablunier** [comment]
Same problem here! Waiting for your PR to be merged, thanks!

**Comment by sebestenyb** [comment]
Sorry @drewm can you please release a minor version with this fix?
Thanks for your work!

**Comment by drewm** [comment]
Sorry, yes, have done. Real life intervened between merging and tagging the release!
