### ISSUE TITLE
SubscriberHash function should be static

### ISSUE THREAD

**Issue by VincentLanglet** [drewm/mailchimp-api#279]
The subscriberHash function return
```
md5(strtolower($email));
```

There is no use of `$this` and no need to create a `Mailchimp` object with an api key.
This function should be static to be used more easily.

**Comment by drewm** [comment]
It only makes sense to use alongside a Mailchimp object, so I don't see why that change is necessary.

**Comment by VincentLanglet** [comment]
> It only makes sense to use alongside a Mailchimp object

@drewm I disagree. When you're using the webhook functionnality, you received request from Mailchimp and you don't need to instantiate any Mailchimp object.
But you still should be allowed to get the subscriber hash from the email.

**Comment by drewm** [comment]
Why do you need to hash the email when _receiving_ a web hook?

Keep in mind that what you're suggesting here is a breaking change.

**Comment by VincentLanglet** [comment]
When I receiving a webhook, I save the user data and his email **and the hash**.
Cause in the user profil, it is allowed for him to modify his email address.

If I need to make a request to Mailchimp, I can't use the email to compute the hash, because the email has _maybe_ changed. I need the previous hash, that is why we kept it.

> Keep in mind that what you're suggesting here is a breaking change.

Why is it a breaking change ?
You still can call the function this way `$this->yourFunction` even if it is static.

**Comment by drewm** [comment]
Is it really that big of a deal to just instantiate the object?

> You still can call the function this way $this->yourFunction even if it is static.

Ah yes, you're right. I was thinking static properties.

**Comment by VincentLanglet** [comment]
> Is it really that big of a deal to just instantiate the object?

Is it really that big of a deal to just declare the method static?

I don't see like a good pattern to instantiate the object when you don't need it.
Plus in my symfony project, I have to inject dependency (an MailChimpApiClient or directly the mailchimp key) just in order to compute the hash. So yeah, I kinda think it's important to not inject a service you could avoid to inject.

I really think that declaring this static function is an improvement without any negative consequences

**Comment by drewm** [comment]
Ok, let's do it.
