### ISSUE TITLE
How do we edit user tags?

### ISSUE THREAD

**Issue by Mujan84** [drewm/mailchimp-api#286]
Hi, Im not sure if this is a missing feature here?

I would expect something like the code below to add the user to this Tag...

$MailChimp->post("lists/".LISTID."/members/$subscriber_hash/tags", [
		'tags' => [
			’Tag Name' => 'active'
		]
	]);

(This is my first post here on GitHub, so bear with me if im doing something wrong here.
Thanks

**Comment by roelofr** [comment]
You can't. It's [not supported by the API](https://mailchimp.com/developer/reference/lists/list-members/list-member-tags/)

**Comment by Mujan84** [comment]
Hi roelofr,
Thanks, I also got this to work today, I would have posted the solution here tonight.
I am now a happy user of this mailchimp-api... all is done on autopilot now:-)
