### ISSUE TITLE
SSL3 issue + param issue

### ISSUE THREAD

**Issue by bobalbert** [drewm/mailchimp-api#34]
Having a couple of issues.

1. missing second param
from your sample code:
$MailChimp = new \Drewm\MailChimp('abc123abc123abc123abc123abc123-us1');
print_r($MailChimp->call('lists/list'));

returns an error for missing second argument. It looks like the call method is expecting a "params" value.

something like print_r( $MailChimp->call( 'lists/list', array( 'nothing' => true ) ) ); of course fixes that issue.

2. again with your basic code example, i'm getting an SSL error from mailchimp:
Mailchimp_HttpError: API call to lists/list failed: SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /Applications/MAMP/htdocs/betterbloodsugar/wp-content/plugins/bbs-mailchimp/src/Mailchimp.php on line 225

It is not until i add curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); into the call method that things seem to work.

It appears that since curl 7.10 this settings is default of True. I'm using curl 7.20.0, thus this explicitly needs to be turned off now. I wonder if prior to 7.10 the default was false.

**Comment by drewm** [comment]
We'll keep an eye on this for the v3 api version.
