### ISSUE TITLE
Plans to make the wrapper support Mailchimp API v3 ?

### ISSUE THREAD

**Issue by Collizo4sky** [drewm/mailchimp-api#38]
Mailchimp currently recommend the v3 of their API. any plans to make this wrapper or create a new wrapper for the v3?

**Comment by drewm** [comment]
Sure, when I get time. The v3 API docs are pretty terrible right now, so I can't see how much work it will be.

**Comment by Collizo4sky** [comment]
The feeling is mutual. info about the v3 API is sparse.

Thanks for this great wrapper.

**Comment by otjutt** [comment]
Thanks for this great wrapper, works like a charm :+1:

**Comment by otjutt** [comment]
Thanks for this great wrapper, works like a charm :+1:

**Comment by ChrisRM** [comment]
I wrote a simple wrapper for v3, pretty similar to @drewm's package. V3 lacks some important features, like creating campaigns etc, but I guess it'll be ready soon. Browsing the [Schema](https://us1.api.mailchimp.com/schema/3.0/) might be the best option to see whats ready and whats not.

Github: [pacely/mailchimp-apiv3](https://github.com/pacely/mailchimp-api-v3)
Packagist: [pacely/mailchimp-apiv3](https://packagist.org/packages/pacely/mailchimp-apiv3)

**Comment by vatps** [comment]
Hello,

I have already written wrapper for Mailchimp v 3.0 wrapper...

https://github.com/vatps/mailchimp-rest-api

P.S. Inspired from  @drewm v2.0 wrapper.

**Comment by drewm** [comment]
See the api-v3 branch.
