### ISSUE TITLE
Is there a way to test API key ?

### ISSUE THREAD

**Issue by dimitrilongo** [drewm/mailchimp-api#41]
I'd like to test the mailchimp api key, to test if the user enter the right one, for example if my api key var is wrong
i have a php notice : 
```notice: Undefined offset: 1 in /MailChimp.php on line 31```
If someone have an idea, maybe be ping the mailchimp API 

Thanks

**Comment by drewm** [comment]
There's nothing in the class to validate the API key. If you wanted to make a PR with that, it would be a nice addition.

**Comment by dimitrilongo** [comment]
thanks for answer, 
```$mailchimp_ping = ($mc->call('helper/ping'));
var_dump($mailchimp_ping);```
that's works, return false on wrong API key or 
```array(1) { ["msg"]=> string(20) "Everything's Chimpy!" } ``` on correct API key

https://apidocs.mailchimp.com/api/2.0/helper/ping.php

but if wrong api key i still have the php notice 
```notice: Undefined offset: 1 in /MailChimp.php on line 31```

**Comment by drewm** [comment]
Right, the code still expects a valid API key.

**Comment by vatps** [comment]
@drewm @dimitrilongo Added Validation Support. Pending PR (https://github.com/drewm/mailchimp-api/pull/42)
