### ISSUE TITLE
Added patch support to wrapper

### ISSUE THREAD

**Issue by leanne616** [drewm/mailchimp-api#44]
Thanks so much for writing this, it has saved me a lot of time. One quick addition - I was having trouble getting my email addresses to update, so added the following to line 100 below case 'delete':

```php
case 'patch':
                    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PATCH');
                    curl_setopt($ch, CURLOPT_POSTFIELDS, $json_data); 
                    break;
```
Thanks!

**Comment by drewm** [comment]
Sounds good - are you able to make a pull request? Otherwise I'll add it when I get a chance.

**Comment by leanne616** [comment]
Hi Drew,

I attempted a pull request, but please let me know if it didn't go through
correctly, since I've not done this before. Thanks again for write the
wrapper, I appreciate your taking the time to put it together!

- Leanne

On Sat, Jul 18, 2015 at 8:10 AM, Drew McLellan <notifications@github.com>
wrote:

> Sounds good - are you able to make a pull request? Otherwise I'll add it
> when I get a chance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drewm/mailchimp-api/issues/44#issuecomment-122535327>.
>



-- 
Leanne Heller

leanne@adaroconsulting.com
www.adaroconsulting.com
p 978-993-0114

Adaro Consulting LLC
*WordPress Web Development*
We focus on business websites and agency partnerships.
