### ISSUE TITLE
returned false when called $MailChimp->get('lists')

### ISSUE THREAD

**Issue by johnqiuwan** [drewm/mailchimp-api#51]
I followed the sample code but received false when called $MailChimp->get('lists')
I am sure the api key is correct, and currently developing under localhost

**Comment by johnqiuwan** [comment]
After I set verify_ssl to false, everything works perfect.
I am just curious the reason why it caused the problem.

**Comment by johnqiuwan** [comment]
I have googled it and found the solution for that.
The problem has been solved

**Comment by katmaha** [comment]
I know this is closed but could you help me out with telling me how you solved it?
I'm having same issue, when I set to false it works otherwise nothing happens. Would appreciate any help.
Thanks!

**Comment by trbsi** [comment]
This is how I did it in __construct() of my own class
```
 $this->mailchimp = new MailChimp($api_key);
 $this->mailchimp->verify_ssl = false; //very important to set to false, otherwise it won't work, every request will return  false
```
