### ISSUE TITLE
API Key not found

### ISSUE THREAD

**Issue by niwlondon** [drewm/mailchimp-api#59]
Suddenly I keep receiving the following error. It was working before, but suddenly has stopped, even though I have changed nothing. I wonder if the key is not being being sent across probably.  The problem happens on two different sites (on different servers).

detail: "Your request did not include an API key."
instance: ""
status: 401
title: "API Key Missing"
type: "http://kb.mailchimp.com/api/error-docs/401-api-key-missing"

**Comment by urg** [comment]
We're getting the same issue

**Comment by drewm** [comment]
Let me know if the issue still persists after that merge.

**Comment by niwlondon** [comment]
Thanks guys for the quick fix, all updated :smile:
