### ISSUE TITLE
cURL fails on Windows servers

### ISSUE THREAD

**Issue by pbscreativeben** [drewm/mailchimp-api#61]
Hi, 

Just a quick note to help anyone else with this issue. 

cURL request fails and just returns false on Windows servers when $verify_ssl = true. Change to false to fix. 

Had to add code to output cURL error message to work out what the problem was. 

Other than that, working nicely with API V3 - thanks.

**Comment by fusioned** [comment]
Can I just concur I am having this issue on my Windows dev machine.
Perhaps a way of making the SSL option configurable without modifying the class source?
