### ISSUE TITLE
API v3 - looks like "PUT" request is not handled (required for updating)

### ISSUE THREAD

**Issue by peteclark3** [drewm/mailchimp-api#62]
in MailChimp.php line 82 - no case for "put"

     switch($http_verb) {
                case 'post':
                    curl_setopt($ch, CURLOPT_POST, true);
                    curl_setopt($ch, CURLOPT_POSTFIELDS, $json_data); 
                    break;

                case 'get':
                    $query = http_build_query($args);
                    curl_setopt($ch, CURLOPT_URL, $url.'?'.$query);
                    break;

                case 'delete':
                    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'DELETE');
                    break;

                case 'patch':
                    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PATCH');
                    curl_setopt($ch, CURLOPT_POSTFIELDS, $json_data); 
                    break;
            }

**Comment by peteclark3** [comment]
Maybe it's not supported in v3?  I tried "put" in their playground and it didn't seem to be working.  Maybe they want us to use "patch" instead.. ?  Ignore if "put" isn't supposed to work..

**Comment by drewm** [comment]
From the below article, I'm inferring that they don't use PUT.

http://kb.mailchimp.com/api/article/what-is-rest

**Comment by drzraf** [comment]
Citing, 2015-10-01 21:14:
> Today we're announcing two changes to API   v3.0 that’ll make it easier to do more with your data in MailChimp. The list members resource now accepts a PUT method that allows you to create or    update a subscriber in a single operation, and we’ve added a batch operations feature that lets you make multiple operations in just one call.

**Comment by drewm** [comment]
Ok, great. Will gladly accept a pull request if anyone's in the position to try it out.

**Comment by wesbos** [comment]
This can be closed, fixed with my latest PR
