### ISSUE TITLE
Not sending opt-in mail?

### ISSUE THREAD

**Issue by intelligence** [drewm/mailchimp-api#66]
Heya,

Splendid wrapper, thanks alot for putting it out there!
I do have some trouble getting it to send out opt-in, it just adds the email to the list..

    $MailChimp = new MailChimp('xxx-xxx');
    $result = $MailChimp->post('lists/xxx/members', array(
        'email_address'     => $email,
        'status'            => 'subscribed',
        'merge_fields'      => array('FNAME'=>$fname, 'LNAME'=>$lname),
        'double_optin'      => true,
        'update_existing'   => false,
        'replace_interests' => false,
        'send_welcome'      => true,
    ));

Does it recognize my IP or something maybe? Any clue?

**Comment by intelligence** [comment]
Ok, so should send "pending" instead of "subscribed", my bad. Thanks again for a great wrap!

**Comment by hugoreaction** [comment]
I have added pending on mine and it still doesn't send a email

**Comment by alexschwarz89** [comment]
Should be added to README.
