### ISSUE TITLE
POST call returns encoded result

### ISSUE THREAD

**Issue by atlza** [drewm/mailchimp-api#67]
Hi,

When using the api V3 branch, I had no errors while using GET to retrieve lists.
But when creating a list, the class returns null. Looking into the code shows me that at this line :  
$result = curl_exec($ch);

$results contains : 
"�<��n� �_�b�%n蔹�Ե�v�@�I,@�D�N��urUG��|��ad/h����ڀ�\�����ZK��jC�m�$N('��ٹQ@�Xk��9ffWwk:#$��~��E ���[��+���n���i�{A�%�6�$�|n1@�#r:��#W�c�rAOyx��FQ�����Z���jJ�<�CLO����9Q:݈i�H�k��>g>��N��/P)��('�<����X�H������z��y���l��f"

I don"t know if it is specific to my case or my server, but I prefer to let you know.
I could fix this by adding this line :  
curl_setopt($ch, CURLOPT_ENCODING, '');

after :  
curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_0);

Maybe it will help someone else.

Regards.

**Comment by marvinschroeder** [comment]
Ran into this issue today! Thank you!
