### ISSUE TITLE
New subscription -> Group (Interests, Sex)

### ISSUE THREAD

**Issue by hugoreaction** [drewm/mailchimp-api#71]
Hello,

In my ML I have two groups Interests-> Cars, Bikes, Boats and Sex-> Male,Female

How do I make a call to subscribe to 1or more interests ?? and only 1 Sex.

Sample:

$result = $MailChimp->post('lists/'.$listID.'/members', array(
                    'email_address'     => $email,
                    'status'            => 'pending',
                    'merge_fields'      => array(
                                                'USERID' => $user_id,
                                                'FNAME'=> $first, 
                                                'LNAME'=> $last, 
                                                'EMAIL' => $email,
                                                'BDAY' => $bday,
                                                'SEX' => $sex
                                                ), // merge_fields array end
                    'interests'         => array( 'Cars' => true, 'Bikes' => true, 'Boats' => false ), // interests is name of group
                    'sex'               => array('male' => true, 'female' => false) // sex is name of group
                ));

**Comment by drewm** [comment]
Rather than using the name like 'Cars', you need to get the ID of that interest and use that instead.

**Comment by aryanpatel** [comment]
I have something similar issue. This is my data being submitted to API at
 `post('lists/my-list-id/members',$postData);`

This is my post data 

```
Array
(
    [email_type] => html
    [email_address] => subscriber@example.com
    [status] => subscribed
    [merge_fields] => Array
        (
            [FNAME] => test
            [LNAME] => test
        )

    [interests] => Array
        (
            [0] => "5130692954"=>true,"84c9981***"=>true,"d02d767***"=>true,"f05d368***"=>true,"474db4e***"=>true,"e9945af***"=>true,"605a592***"=>true
        )

)
```

But I get this error

```
Array
(
    [type] => http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/
    [title] => Invalid Resource
    [status] => 400
    [detail] => The resource submitted could not be validated. For field-specific details, see the 'errors' array.
    [instance] => 
    [errors] => Array
        (
            [0] => Array
                (
                    [field] => interests
                    [message] => Schema describes object, array found instead
                )

        )
)
```

Can you help me solving this issue?
