### ISSUE TITLE
Resource Not Found error from MailChimp when trying to patch a new subscriber

### ISSUE THREAD

**Issue by krixmeister** [drewm/mailchimp-api#75]
Hi - thanks for providing this wrapper. I'm upgrading from the v2.0 wrapper, and having some trouble doing a simple update. get('lists') works, so connectivity is there, but the following code:

```php
$MailChimp = new MailChimp('myapicodehere-us12');
$list_id = '24c23b0042';
$subscriber_hash = $MailChimp->subscriberHash('person@example.com');
$result = $MailChimp->patch("lists/$list_id/members/$subscriber_hash", array(
                'merge_fields' => array('FNAME'=>'Firstname', 'LNAME'=>'Lastname')
            ));

print_r($result);

```

returns following:

Array ( [type] => http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/ [title] => Resource Not Found [status] => 404 [detail] => The requested resource could not be found. [instance] => )

  I've triple-checked the list_id, and am reasonably confident it is correct - both from checking the MailChimp website, and checking the returned ID from get('lists').
  I should point out that due to version issues on my production server, I've had to comment out the namespace - but as noted, this did not seem to effect the get('lists') and as this is test code, there should not be any namespace collisions.

  Any ideas or pointers on what I'm doing wrong would be greatly appreciated!

**Comment by drewm** [comment]
Is the subscriber `person@example.com` definitely on the list?

**Comment by krixmeister** [comment]
Hi thanks for quick reply. Same error occurs whether the subscriber is already on the list, or not. Goal is to set the flag `'status_if_new' => 'subscribed'` so that new addresses are subscribed, existing addresses are untouched - but for now, just trying to get a new user subscribed.

**Comment by drewm** [comment]
It's definitely working for me when the email address is already on the list. Here's what I'm using:

```php
$list_id = '18......09';
$memberID = 'c..............................2';
$member_hash = $MailChimp->subscriberHash('drew.mclellan@gmail.com');

$result = $MailChimp->patch("lists/$list_id/members/$member_hash", [
		'merge_fields' => ['FNAME'=>'Drew', 'LNAME'=>'Is Patched'],
	]);
	
```

**Comment by krixmeister** [comment]
OK - you can close this issue - it was totally a typo on my part, which to make matters worse I didn't copy to the above code properly. Having done so would have made it much easier for you to have seen the error! Apologies for the wild goose chase...

Anyway, thanks. One thing for future reference - although the code is in fact compatible with PHP5.3, it may be worth noting to users that the examples in the readme require PHP5.4 or higher due to [array dereferencing](http://php.net/manual/en/migration54.new-features.php)

**Comment by drewm** [comment]
Oh perfect, no problem. Glad you're up and running.

**Comment by Slavezax** [comment]
To anyone comes here from Google search via the same error, the list ID is not the same ID as you see in the URL. Go to your list>settings>list name and defaults to see requested ID.

**Comment by kilobyte2007** [comment]
@Slavezax Thanks man, you saved my day!

**Comment by costibotez** [comment]
@Slavezax mine too

**Comment by golaphazi** [comment]
Follow this code below:

`$data = [
			'email_address' => (isset($email) ? $email : ''),
			'status' => 'subscribed',
			'status_if_new' => 'subscribed',
			'merge_fields' => [
				'FNAME' => (isset($firstname) ? $firstname : ''),
				'LNAME' => (isset($lastname) ? $lastname : ''),
				'PHONE' => (isset($phone) ? $phone : ''),
			],
		];
		$server = explode('-', $token);
        $url = 'https://'.$server[1].'.api.mailchimp.com/3.0/lists/'.$list.'/members/';

		$response = wp_remote_post( $url, [
			'method' => 'POST',
			'data_format' => 'body',
			'timeout' => 45,
			'headers' => [
							
							'Authorization' => 'apikey '.$token,
							'Content-Type' => 'application/json; charset=utf-8'
					],
			'body' => json_encode($data	)
			]
		);
		if ( is_wp_error( $response ) ) {
		   $error_message = $response->get_error_message();
			$return['error'] = "Something went wrong: $error_message";
		} else {
			$return['success'] = $response;
		}`

Must be include merge_fields filed into body data...

**Comment by ryancwalsh** [comment]
Thank you, @Slavezax !

**This has been moved to https://us19.admin.mailchimp.com/audience/ > Manage Audience > Settings > Audience name and defaults > Audience ID**

**Comment by ashieachiri** [comment]
I am currently facing this issue. any help?

**Comment by variyabhargavwc** [comment]
Not working for me when the email address is not exist in list. Here's what I'm using:

```
$listId= '18......09';
$subscriberHash = md5(strtolower($email));
$url = "https://$serverPrefix.api.mailchimp.com/3.0/lists/$listId/members/$subscriberHash/events";

      $data = [
        "name" => "test_event",
        "is_syncing" => false,
        'properties' => [
          'first_name' => 'John',
          "variants" => json_encode([
            ["color" => "red", "size" => "M"],
            ["color" => "blue", "size" => "L"]
          ])
        ]
      ];
```

Is it compulsory to first add an email address to the list then after called endpoint lists/$listId/members/$subscriberHash/events ?
