### ISSUE TITLE
Update Bach

### ISSUE THREAD

**Issue by diegolorenzomolinero** [drewm/mailchimp-api#80]
Hi! 
How to update/insert in bacth process? and merge fields
Thanks

**Comment by drewm** [comment]
Hello.

According to the API documentation (that you have access to) batches can be created and read:
http://developer.mailchimp.com/documentation/mailchimp/reference/batches/

For an example of using this library to create a batch, see the README:
https://github.com/drewm/mailchimp-api#batch-operations
