### ISSUE TITLE
Query parameters

### ISSUE THREAD

**Issue by pimduijst** [drewm/mailchimp-api#81]
Hi,

I have a question, how can I pass query parameters to the endpoint? For example as mentioned on this documentation page:

http://developer.mailchimp.com/documentation/mailchimp/reference/lists/abuse-reports/

Kind regards,

Pim

**Comment by drewm** [comment]
It should be the same as everything else:

```php
$MailChimp->get("/lists/$list_id/abuse-reports", [
    'count' => 1
]);
```

and so on.
