### ISSUE TITLE
[PATCH-ISSUE] This resource has not yet implemented array assignment for options.choices.

### ISSUE THREAD

**Issue by anaelChardan** [drewm/mailchimp-api#82]
@drewm With your advice I open a new issue : here is my problem 

I want to update merge-fields of a list using this : 

```
$MailChimp->patch('lists/$listId/merge-fields/$merge-field-id',
            [
                 'name' => 'Country',
                 'type' => 'dropdown',
                 'options' => ['choices' => [1 => 'USA']]
             ]
);
```

And the error is 'This resource has not yet implemented array assignment for options.choices.' but it seems that I give the good fields with the good formatting no ? Thanks :)

**Comment by drewm** [comment]
`1` doesn't look like the sort of ID MailChimp would normally give for a choice option. Make sure you're using the correct ID.

**Comment by anaelChardan** [comment]
Also without the 1 I have the same problem

```
 $data =
            [
                'name' => 'Country',
                'type' => 'dropdown',
                'options' =>
                 ['choices' => ['TEST']]
            ];
```

![screenshot from 2016-02-19 09 56 52](https://cloud.githubusercontent.com/assets/6115681/13170824/3d32d8a0-d6ef-11e5-8da9-c081f1a9d40a.png)

**Comment by anaelChardan** [comment]
So, I send a mail to MailChimpSupport API and they answer me, so it's a bug on their side

Hey there Anaël,

Thanks for writing in. I'm happy to help out with the error being seeing.

While our documentation indicates that choices should be an array for drop down and radio button merge fields, the error message says that array assignment hasn't been implemented for it yet.

I was able to test this out in my own account and received the same error message. This is definitely unexpected, so I've passed it along to our developers. Unfortunately, I wouldn't be able to provide a timeframe for when this will be fixed. As soon as a fix is found, it will be pushed live.

In the meantime, these options can be updated using v2.0 and the /lists/merge-var-update method. You can find the documentation for that here:

https://apidocs.mailchimp.com/api/2.0/lists/merge-var-update.php

Thanks again for bringing this to our attention. If you have any further questions, please don't hesitate to get back in touch. We're always happy to help!

Cheers,
Steff
