### ISSUE TITLE
ErrorException in AliasLoader.php line 66: Class 'Drewm\MailChimp' not found

### ISSUE THREAD

**Issue by dukenst2006** [drewm/mailchimp-api#86]
Hello,
In my laravel project 5.1, I have this line 'Mailchimp' 	=> 'Drewm\MailChimp' on my config/app.php file in aliases. it worked well with Laravel 5.0, now I make an update to Laravel 5.1, it gives me this error : ErrorException in AliasLoader.php line 66: Class 'Drewm\MailChimp' not found. 
Any Idea? please help me with this error! Thanks!

**Comment by drewm** [comment]
You'd be best to ask some Laravel people.
