### ISSUE TITLE
PUT returns an error and is required by MailChimp to (update or add unsubscribed user)

### ISSUE THREAD

**Issue by hugoreaction** [drewm/mailchimp-api#87]
Hello I have talked to MailChimp guys and they told me we must use PUT call in order to subscribe ("returning") user, people that were once on the list but have unsubscribed.

The error I get when I make the PUT call is:

======================================

object(stdClass)#63 (5) {
  ["type"]=>
  string(77) "http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/"
  ["title"]=>
  string(18) "Method Not Allowed"
  ["status"]=>
  int(405)
  ["detail"]=>
  string(113) "The requested method and resource are not compatible. See the Allow header for this resource's available methods."
  ["instance"]=>
  string(0) ""
}

======================================

I am trying to solve this on my own if I do I will post the answer here, but for now I could use some help thanks!

**Comment by Jarlskov** [comment]
It's pretty hard to help with no clue of what you're trying to do, but I havn't had any issues using put, to a URL like lists/$list_id/members/$user_hash - it works as expected.

**Comment by hugoreaction** [comment]
The one I am using and have downloaded from here does not Hash email and I think that is the problem.. I believe I have fixed it, I had to read trough the MailChimp docs

**Comment by Jarlskov** [comment]
There's an example in the [documentation](https://github.com/drewm/mailchimp-api) showing how to create a subscriber hash. The documentation uses it for a patch request, but it's the same general idea.

**Comment by hugoreaction** [comment]
yeah I just changed this and it works

$url = $this->api_endpoint.'/'.$method .'/' . md5($args['email_address']);

and that did it.. otherwise it failed every time.. I guess they changed the URL to require email to be included and hashed .. But you might want to look at your code as it didn't work for me with out that hash .. Thanks Jarlskov!
