### ISSUE TITLE
include it manually?

### ISSUE THREAD

**Issue by tyranni** [drewm/mailchimp-api#95]
Sorry for the stupid question ;)
Unfortunately I could not use composer. So, I have to go the manually way. 
I don't understand where I have to put the "include('./MailChimp.php');" into. Into the setup.ts? Or into the configuration file of the "koning_mailchimp"-extension which I want to use?
Would be very very happy if someone gives me a hint.

Thank you and best regards! :)

**Comment by drewm** [comment]
Include the class in the file where you want to write your MailChimp code.

**Comment by tyranni** [comment]
thank you for your answer! 
O.K., that means no Typo3-file has to be changed and I have to do the changes somewhere in the "koning_mailchimp"-extension. 
Thanks again and best regards! :)
