### ISSUE TITLE
Invalid Resource - 400

### ISSUE THREAD

**Issue by prabupertly** [drewm/mailchimp-api#97]
I'm trying to update the Campaign HTML content using this function.

`$campaignsContent = $MailChimp->put('campaigns/'.$campaigns['id'].'/content', array('html' => $mailContent));`

But i'm getting this error. HTML is perfect & also i m passing valid `campaign_id` to the campaign.
`Array
(
    [type] => http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/
    [title] => Invalid Resource
    [status] => 400
    [detail] => The resource submitted could not be validated. For field-specific details, see the 'errors' array.
    [instance] => 
    [errors] => Array
        (
            [0] => Array
                (
                    [field] => 
                    [message] => Schema describes object, NULL found instead
                )

        )

)`

**Comment by drewm** [comment]
Have you spoken to MailChimp about it? This wrapper doesn't have code for each particular method - they're all treated as being the same. If this one method is failing it could indicate an API issue.
